### ISSUE TITLE
Remove (to be) deprecated templates and variables in next major, new defaults

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#244]
### List of to be removed template variables:
See https://github.com/SwiftGen/SwiftGenKit/issues/5

### List of to be removed/renamed templates:
See https://github.com/SwiftGen/templates/issues/11

### Other things to remove

- `--enumName`: replaced by CLI parameter, template should provide default
- `--sceneEnumName`: same as above
- `--segueEnumName`: same as above
- `--import` no longer used, replaced by `modules` context variable

**Comment by AliSoftware** [comment]
We should also remove deprecated templates (or maybe you planned to create a dedicated issue for them)?

* Make Swift 3 the new default template in the next major, moving the Swift 2 templates to opt-in
* Maybe remove "structured" templates as "dot-syntax" are way better anyway ?
* Probably make "dot-syntax" the default template for any subcommand that has a dot-syntax (images, strings), and move the non-dot-syntax ones as opt-in ?

**Comment by djbe** [comment]
No, let's also do that here, we'll create dedicated PR's for each sub item

**Comment by AliSoftware** [comment]
> * storyboards:
>   * lowercase: no idea
This one was originally created to address #111

Not sure if it's still relevant in Swift 3, haven't looked in details about the consequences regarding that.

**Comment by djbe** [comment]
Seems like a really specific use case, better just rename the scene to something non-conflicting, or use a custom template.

**Comment by AliSoftware** [comment]
That is actually not so uncommon, I've encountered that as well, and it's very common to chose the name of the class as the scene identifier (use `"DetailViewController"` for the scene identifier of a scene of class `DetailViewController` for example), like most people do for `UITableViewCells` and their `reuseIdentifier` as well.

The solution we used was to duplicate the bundled template to make a custom one, adding the name of the App (= the name of the _module_ that's associated with the app target) in front of every `customClass`.

Note that if we implement the `--param foo=bar` feature in the future to pass arbitrary parameters to the command line, we could imagine a `--param appModuleName=MyAwesomeApp` that would be used when `customModule` is empty, instead of using no prefix at all, and that would solve #111 altogether. So maybe we could get rid of `storyboards-lowercase` indeed but it would then be good to implement the `--param foo=bar` CLI flags soon after to give a way to overcome this #111 issue ;)

**Comment by djbe** [comment]
True. There's no other way to avoid these collisions? The enum inside an extension works here (playgrounds):
```swift
struct T {
}

extension T {
	enum Bla {
		case a
		case b
	}
}

T.Bla.a```

**Comment by AliSoftware** [comment]
The problem isn't embedding the `enum` in an `extension`. The problem is that if the return type is `Bla` and the name spacing `enum` is also named `Bla`, then it becomes ambiguous:

```swift
enum DetailsViewController {
  static func instantiateDetailsViewController() -> DetailsViewController {
    guard vc = self.storyboard.initialViewController as? DetailsViewController else {
      fatalError(…)
    }
    return vc
  }
```

Here on line 2 the return type is `DetailsViewController` because it's supposed to return an instance of that *class* which is supposed to be a `UIViewController` subclass. But in fact the compiler confuses that with the enum of the same name. Same for the `as? DetailsViewController` on line 3, which would in this case always fail because it tries to cast to the enum type, no to the class type of the same name.

And the enum happen to have the same name as the class just because the Storyboard happens to have the same name as well, which is actually quite common (at least I have a lot of storyboards with only one scene and name them the same as the scene class, like `DetailsViewController` — that's how I use my `Reusable` pod and its `StoryboardBased` protocol, btw.

**Comment by djbe** [comment]
Hmm, say we implement the func for type mentioned in #243, the template could test if it's equal to the enum name:
```
{% func enumNameFor storyboard %}
... result = storyboardName ...
... for loop through scene types ...
    ... if type == result ...
        ... result = result + "type" ...
{% endfunc %}
```

**Comment by AliSoftware** [comment]
I think there's way much more `variables` to remove. Including all the ones I've added at the beginning of SwiftGen just because Stencil didn't have the tags to build some strings via the template syntax so I built them natively, but now that it's possible (and could be exposed as a `{% macro %}` even) they should be removed.
