### ISSUE TITLE
how can i have both -t swift3 and -t lowercase together for storyboards?

### ISSUE THREAD

**Issue by ashkanpower** [SwiftGen/SwiftGen#248]
everything i try doesnt work

things i tried :
1. swiftgen storyboards -t swift3 -t lowercase --output $TARGET_NAME/SwiftGen/UIStoryboard+Assets.swift .

2. swiftgen storyboards -t swift3 lowercase --output $TARGET_NAME/SwiftGen/UIStoryboard+Assets.swift .

3. swiftgen storyboards -t swift3, lowercase --output $TARGET_NAME/SwiftGen/UIStoryboard+Assets.swift .

4. etc...

**Comment by AliSoftware** [comment]
`-t` selects à template. By definition, a template is a model for the code to be generated (and not, like, a set of rules or something), so you can only be based on a single template, not multiple templates.

* You can see all the templates available using the `swiftgen templates list` command.
* You can see the content of a given template using `swiftgen templates cat <name-of-the-template>` (the name being the one as listed by `swiftgen templates list`, so the full name prefixed by `storyboards` for storyboard templates). For example `swiftgen template cat storyboards-swift3` etc
* if you don't find the template which match your needs, is really easy to create your own template to better match you code style. Simply duplicate an existing template to have a starting point (e.g. `swiftgen templates cat storyboards-swift3 >storyboards-my-custom-one.stencil`), modify it to your likings, then use it via `-p`

See the `documentation/templates.md` documentation for more information, everything is explained there.

**Comment by djbe** [comment]
Can I ask why you'd need to combine `lowercase` (a Swift 2.3 template) with the `swift3` template? Swift 3 enum cases are by default lowercased (on the first word).

**Comment by djbe** [comment]
Ah it's about the enum names themselves, related to #111 then.

**Comment by AliSoftware** [comment]
@ashkanpower It your problem is the one explained in #111 (i.e. the name of the storyboard file, from which the enum name is derived, is the same as the name of your VC class), then rather than creating a template which would make the `enum` names lowercase (and not matching the Swift 3 naming conventions anymore), there are better solutions to overcome this limitation:

1. One solution would be to duplicate the `storyboards-swift3` template (see explanations on my previous comment and in the documentation), then prefix or suffix the enum names in the template by something of your liking (say "SB"), especially [here line 54](https://github.com/AliSoftware/SwiftGen/blob/master/templates/storyboards-swift3.stencil#L54) and [here line 96](https://github.com/AliSoftware/SwiftGen/blob/master/templates/storyboards-swift3.stencil#L96)
2. Another solution would be to duplicate the `storyboards-swift3` template too, but then instead of changing the enum names being generated, always use the full name in the return type of the `static func` in the templates, like [here on line 72](https://github.com/AliSoftware/SwiftGen/blob/master/templates/storyboards-swift3.stencil#L72). You can see here that if the `scene` has a `customModule`, then it's used as a prefix before the custom class (`{% if scene.customModule %}{{scene.customModule}}.{% endif %}` right before `{{scene.customClass}}`). You could modify your copy of the template so that if there's no custom module for your scene, use your app module name (hardcoded in the template) instead, like: `{% if scene.customModule %}{{scene.customModule}}{% else %}MyAwesomeApp{% endif %}.{{scene.customClass}}`. This way, all storyboard scenes that don't have a custom module set in interface builder will explicitly use `MyAwesomeApp` as the module name (where `MyAwesomeApp` is obviously the name of your app target)
3. Last solution would be to give all of your storyboard scenes an explicit module name. This is easy to do: on each storyboard in Interface Builder, be sure not to left the "Module" field blank, and instead set it to the name of your app target. This way it will be picked and used by SwiftGen as the `scene.customModule` and disambiguate everything, allowing you to use the `-t swift3` template without any issue.

**Comment by AliSoftware** [comment]
I'm closing this as solutions has been posted in comments and also given that the next version of SwiftGen will always pick the right module even if not set (thanks to the use of the new `env.PRODUCT_MODULE_NAME` coming soon)
