### ISSUE TITLE
Add info about the input file in the output's header 

### ISSUE THREAD

**Issue by Czajnikowski** [SwiftGen/SwiftGen#250]
Hi!

How about adding input file path in the top section of the output file? It might be useful info in addition to the current:

`// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen`

😉

**Comment by AliSoftware** [comment]
Hi!
Thanks for the suggestion.

The problem with doing that is the input file path is different from machine to machine. This does not goes well when working with multiple contributors on the same project, who would certainly have checked out the project repository in a different directory path/name each.

For example Alice could end up with a header containing `Generated from: /Users/alice/dev/work/awesome-project/Resources/Localizable.strings`. She would then commit the generated file and push it to the git remote.
But then Bob would do a `git pull`, recover Alice's version, but if they added SwiftGen as a build phase like most people do in their projects,  next time Bob builds the project he would regenerate the same file with the exact same content… except that header which would have changed to: `Generated from: /Users/bob/Documents/iOS-Dev/awesome-project/Resources/Localizable.strings`, leading to a useless git diff every time.

And we couldn't even try to guess a local path relative to the project either, since environment variables are resolved by the shell, so before the shell pass the path to SwiftGen, so SwiftGen never sees env variables like `$PROJECT_DIR` and similar since they're already substituted by the shell beforehand.

**Comment by AliSoftware** [comment]
Closing this now due to lack of activity and problems explained above that would arise for users if we decided to do this
