### ISSUE TITLE
Update release script

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#266]

**Comment by AliSoftware** [comment]
We might want to migrate the release script in https://github.com/SwiftGen/shared, and that repo could act as a "hood" / "top" project for transverse contributions and transverse actions/scripts.

Btw it could be nice to have a better name for that transversal and hood repo, maybe like "Eve" or something?

**Comment by AliSoftware** [comment]
I've updated the Rakefile so that the next time we need to do a release (4.2.1) it's already ready and should work just for that.

But that doesn't close that issue, as I still want to:

* Move that `Rakefile` in https://github.com/SwiftGen/Eve
* clean it up a bit, even maybe split it into multiple Rakefiles (either all in Eve but for better readability, or one Rakefile per project knowing how to build and release each, and a global one in Eve)
* Probably make use of OctoKit for easier GitHub automation (especially since we'll extend the Rakefile tasks to some other stuff like creating GH projects etc)

**Comment by djbe** [comment]
I'd prefer the multiple rakefiles as each repo is quite a bit different (templates <--> kits <--> swiftgen).

**Comment by djbe** [comment]
Closing this, last remaining item (use OctoKit) moved to separate issue in Eve repo.
