### ISSUE TITLE
SwiftGen 4.2 Swift 3.0 incompatibility

### ISSUE THREAD

**Issue by lovesuper** [SwiftGen/SwiftGen#272]
Lib/Fonts.swift:39:17: 'fontNamesForFamilyName' has been renamed to 'fontNames(forFamilyName:)'
Lib/Fonts.swift:25:18: 'NSBundle' has been renamed to 'Bundle'

in generated code for Fonts

[screenshot](http://joxi.ru/l2ZG6WUwlW3nAJ.jpg)

**Comment by AliSoftware** [comment]
According to your screenshot it seems to me that you are not using the `swift3` template when invoking `swiftgen`, so that's normal.

You should use `-t swift3` to use the template dedicated to Swift 3. See the README for more info: there's a dedicated section there about Swift 3 explaining it in details.

**Comment by lovesuper** [comment]
Thank YOU. I have missed it.
