### ISSUE TITLE
Identifiers starting with numbers

### ISSUE THREAD

**Issue by mikkelam** [SwiftGen/SwiftGen#289]
I have a font named 25UltraLight from helvetica neue font family, when using swiftgen it generates the following enum case:
```
  enum HelveticaNeueLTStd: String, FontConvertible {
    case 25UltraLight = "HelveticaNeueLTStd-UltLt"
  }
```
which is not accepted in swift, is there any way to handle this? Or is this a bug that needs to be fixed

**Comment by AliSoftware** [comment]
Mmmh that's strange because the `swiftIdentifier` filter is supposed to handle that and prefix the font name with an underscore to avoid the problem in such cases… : https://github.com/SwiftGen/templates/blob/master/templates/fonts-swift3.stencil#L56

Which SwiftGen version are you using, and which template?

**Comment by mikkelam** [comment]
version
```
SwiftGen v0.0 (Stencil v0.8.0, StencilSwiftKit v1.0.0, SwiftGenKit v1.0.1)
```
command im running
```
swiftgen fonts fonts/ -t swift3 -o Fonts.swift
```

**Comment by AliSoftware** [comment]
Ok thx. Looks like a bug then 😕 will take a look

**Comment by djbe** [comment]
Weird, because we do have a test for this situation:
https://github.com/SwiftGen/StencilSwiftKit/blob/master/Tests/StencilSwiftKitTests/SwiftIdentifierTests.swift#L40

We might want to move this issue to StencilSwiftKit.

**Comment by djbe** [comment]
@mikkelam Could you make a quick custom template copy, and switch around the `swiftIdentifier` and `snakeToCamelCaseNoPrefix` filters? Should look like this:
```case {{font.style|snakeToCamelCaseNoPrefix|swiftIdentifier|lowerFirstWord|escapeReservedKeywords}} = "{{font.fontName}}"```

I think the snakeToCamelCase filter is throwing away the `_` prefix.

**Comment by mikkelam** [comment]
@djbe That seemed to do the trick, now I'm getting
```
enum FontFamily {
  enum HelveticaNeueLTStd: String, FontConvertible {
     case _25_Ultra_Light = "HelveticaNeueLTStd-UltLt"
  }
}
```

**Comment by AliSoftware** [comment]
Nice catch @djbe !

**Comment by djbe** [comment]
@mikkelam Am I correct in assuming that the font's name is actually "25 Ultra Light"? (with spaces)

Right, that's the "quick fix", but it isn't a solution. A correct identifier would actually be `_25UlraLight` (removing the extra underscores). We could change the template to use `snakeToCamelCase` instead of `snakeToCamelCaseNoPrefix`.

**Comment by mikkelam** [comment]
> @mikkelam Am I correct in assuming that the font's name is actually "25 Ultra Light"? (with spaces)

Yes, you are right
