### ISSUE TITLE
Improvement: Accept -p or --templatePath when using templates command

### ISSUE THREAD

**Issue by jeremiegirault** [SwiftGen/SwiftGen#308]
Hi here, thank you for the good work

Description :
I wanted to submit a possible improvement: almost all commands support a `-p` or `--templatePath` however the only one who don't is... `templates` !
I feel a bit sad because I can't list the custom templates provided in my own repo.
It would be great to accept this parameter in the `templates` commands and subcommands

Informations:
- *SwiftGen Version*: 4.2.1
- *Xcode version*: 8.3.2 (8E2002)
- *Target OS*: Not relevant
- *Stack Trace*: none

**Steps to reproduce**
`swiftgen templates list --templatePath ./templates` where `./templates` is a valid directory containing templates.
**Expected Result:**
List templates including the ones in the provided directory
**Actual Result:**
`Unknown Arguments: --templatePath ./templates`

**Comment by AliSoftware** [comment]
Hi Jay

I'm not sure I understand the use case here? 
The `swiftgen templates list` command is mainly designed to list all the templates in the search paths that swiftgen will look into when you use `-t` / `--templateName`, because when you use that option you only provide a name and this have to know which possible names are accepted. We thus list all the named templates that `-t` would be able to use, contained either inside of SwiftGen or in AppSupport.

When you use a custom template from your `./templates` local directory you won't use a name and `-t` but will use a full path. To list all the templates in that directory a simple `ls **/*.stencil` would suffice. And nothing prevents you to organize your templates however you want in that `./templates` directory of yours anyway (organize by folders or a flat hierarchy) and name them however you like too (e.g. `l10n.template` maybe), as you'll specify the path when invoking SwiftGen (and not a name) anyway. So I'm not sure how `swiftgen templates list -p ./templates` would (1) detect which files are templates (you can give them the extensions you prefer), (2) know for which subcommand they would be (you can name your template files however you like), and (3) be relevant, as it won't allow you to use the templates names that it would list anyway so what it would print wouldn't even be usable

**Comment by jeremiegirault** [comment]
Ah ok I expected that templates should follow the `subcmd-customname.stencil` nomenclature and therefore I was trying to test wether SwiftGen would recognize my custom templates :
<img width="171" alt="capture d ecran 2017-05-23 a 21 13 44" src="https://cloud.githubusercontent.com/assets/1162682/26371997/c17cfb50-3ffc-11e7-8976-c66f0ba5484c.png">

I was expecting to be able to do something like `swiftgen font -t myProject -p ./templates` which is not so clear when reading the README :

> Bundled templates vs. Custom ones
> SwiftGen comes bundled with some default templates for each of the subcommand (colors, images, > strings, storyboard, fonts…), but you can also create your own templates if the defaults don't suit  your coding conventions or needs. Simply store them in ~/Library/Application  Support/SwiftGen/templates, then use the -t / --template option to specify the name of the template to use, or store them somewhere else (like in your project repository) and use -p / --templatePath to specify a full path.

Following your point I discovered https://github.com/SwiftGen/SwiftGen/blob/master/documentation/Templates.md which goes more in details about custom templates. Actually it would be quite practical to have a relative directory convention for custom templates in order for templates to be shared using source control while have simple command line calls
e.g. looking for a .swiftgen directory in the current working directory for custom templates + being able to run `swiftgen font -t custom`

Actually I understand your point, consider this issue more like a feedback from a first-time user. It may bring something interesting

**Comment by AliSoftware** [comment]
Thx for the feedback

All your concerns will be addressed very soon, pending Swiftgen 5.0 release

* The use of both `-t` and `-p` simultaneously will be forbidden (already implemented: https://github.com/SwiftGen/SwiftGen/pull/300)
* The way templates are organised for named templates (templates provided by SwiftGen and accessible via `-t <name>` for convenience) will change soon anyway (https://github.com/SwiftGen/SwiftGen/pull/304)
* The documentation about Templates is planned to be improved a lot (see SwiftGen#305 among others) and will be completed by the improved documentation of https://github.com/SwiftGen/SwiftGenKit which is the code module of Swiftgen parsing the input resources and generating the data/context for the templates
