### ISSUE TITLE
Throw error if string positional parameters with the same index have a different type

### ISSUE THREAD

**Issue by NachoSoto** [SwiftGen/SwiftGen#309]
See https://github.com/SwiftGen/SwiftGen/issues/6#issuecomment-304392849.

Right now, a localized string like `Text: %1%@; %1%@.` produces an `enum` case with 2 associated values instead of only 1.

An edge case to look for (I'd say `SwiftGen` should fail with an error) is if the types differ, like `Text: %1%@; %1%d.`.

**Comment by djbe** [comment]
I think that edge case you mentioned would crash at runtime, so we should indeed error out.

**Comment by djbe** [comment]
Is `%1%@` a new syntax? Because the syntax I'm seeing everywhere is `%1$@`, which does work correctly. I tried it with a new (extra) test in SwiftGenKit, and it works as expected.

We should still handle the edge case you mentioned, because currently the last instance of the placeholder overwrites previous instances' types.

**Comment by NachoSoto** [comment]
Oh you're totally right, I just got the syntax wrong!

**Comment by AliSoftware** [comment]
Ahah great minds, I just realized that myself too and commented on the other issue ^^
