### ISSUE TITLE
Finding unused strings in the project

### ISSUE THREAD

**Issue by emartynov** [SwiftGen/SwiftGen#322]
Hi guys,

I'm trying to solve the particular problem - finding unused strings in the project.
None of tools is helping because enums values are used in extension function, so at least used once.

I wonder why you choose to go for enums with comment and extension function, instead of going to more sophisticated enum which holds translation string itself.

How do you solve a similar problem?
What was drive to make code generation in this way?

**Comment by AliSoftware** [comment]
Hi !

By "enum which holds the translation string itself" I assume you mean an enum with a string rawValue, as in `enum L10n: String` then `case aKey = "aLocKey"`?

It's not possible to go that route because we use associated values in the generated enum (when your Localizable strings contains `%d/%@/…` placeholders) and an enum with associated values can't also have a rawValue

**Comment by emartynov** [comment]
I'm not a Swift developer (so I might say something completely stupid), but I saw that with enums it is possible to do something like:
```
enum Barcode {
 case UPCA(Int, Int, Int, Int)
 case QRCode(String)
}
```

**Comment by AliSoftware** [comment]
Yes and this is exactly what we do. That's called "enums with associated values" as I mentioned in my previous comment, and that's what we use In our templates.

**Comment by emartynov** [comment]
Then probably our iOS devs are using the wrong template. I see generated code like:
```
enum TheTranslate {
  /// Available balance
  case accountsAccessibilityAvailableBalance
}

extension TheTranslate: CustomStringConvertible {
  var description: String { return self.string }

  var string: String {
    switch self {
      case .accountsAccessibilityAvailableBalance:
        return YLTTranslate.tr(key: "accounts__accessibility_available_balance")
   }
}

```

**Comment by AliSoftware** [comment]
Again, we generate associated values with the enums only when there are associated values in the Localizable strings, namely when your Localizable strings use placeholders.

So, if none of the strings in your `Localizable.strings` use any `%f`/`%@`/`%d`/… printf-style placeholder — expecting a value to be used for that placeholder at call site — then non of the generated enums will have an associated value.
But in general, in a typical project you'll likely have some Localizable strings that are actually localised printf-style formats, and then for those we generate associated values for the corresponding enums, because that's exactly the kind of use case Swift's associated enum feature are fit for.

So if your Localizable.strings contains this:
```
"AccountsBalanceTitle" = "Your account's balance";
"Welcome" = "Hello, dear %@";
"AccountsAcessibilityAvailableBalance" = "Your available balance is $ %f.";
"Continue" = "Continue";
```
Then the generated enum will look like:

```swift
enum TheTranslate {
  /// Your account's balance
  case accountsBalanceTitle
  /// Hello, dear %@
  case welcome(p0: String)
  /// Your available balance is $ %f.
  case accountsAcessibilityAvailableBalance(p0: Float)
  /// Continue
  case continue
}
```

Notice that the two strings containing placeholders generate cases with associated values.
This allows to leverage strict type-safety in your code, by enforcing you to provide a parameter when using that translation in your code, instead of forgetting to provide a value for the placeholder or providing a value of the wrong type (e.g. Int instead of String, etc) and what makes the usage of this template powerful — because you avoid risks of having crashes like EXC_BADACCESS that could otherwise happen if you provided the wrong placeholder, while using SwiftGen and this template the compiler will now prevent you to accidentally make such mistake.

This construct provides lots of advantages and leverage the power of associated values to make your code safer when using placeholders and printf-style strings.

Please read the README and look at the playground for more info, where all these examples and use cases are described.

**Comment by emartynov** [comment]
Ok, I will rename issue title. How do you guys are looking for strings that are not used?

**Comment by djbe** [comment]
Just a small note for SwiftGen 5.0 users: we no longer use cases with associated values, but instead use static constants (`let`). See for example:
https://github.com/SwiftGen/templates/blob/master/Tests/Expected/Strings/flat-swift3-context-multiple.swift

**Comment by AliSoftware** [comment]
@emartynov it's not SwiftGen's own goal to find unused strings in the project, I mean it's not what SwiftGen has been built for.

Also, as @djbe said, the new templates in latest SwiftGen version 5.0 use `static let` for strings without parameters/placeholders, and `static func` for strings with parameters. That should make it easier for other tools to detect if those constants or functions are unused.

**Comment by emartynov** [comment]
Guys, I'm glad that with SwiftGen we don't operate with strings anymore and have compile errors about missing translations.

However, this also removed nice AppCode feature report about unused localisation.

I'm going to close issue since SwiftGen 5.0 probably fixes it for us.

P.S. I know storage wise it is not a big problem. I know that not many people are using AppCode.
