### ISSUE TITLE
Support Xcode 9 on macOS 10.13

### ISSUE THREAD

**Issue by fxcoudert** [SwiftGen/SwiftGen#330]
swiftgen 5.1.1 [fails to build](https://gist.github.com/f5a612b495089a55c1af08598b4c217c) on macOS 10.13 (beta 7) with Xcode 9 (beta 6):

```
[!!!] SwiftGen requires Xcode 8.*, but we were not able to find it. If it's already installed update your Spotlight index with 'mdimport /Applications/Xcode*'
```

This showed up during our check of Homebrew formulas for 10.13 compatibility.

**Comment by AliSoftware** [comment]
Thx for the issue @fxcoudert !

@djbe What seems strange to me is that I thought we now _did_ require Xcode 9 to build (after our recent changes about Swift 4 support etc) so how come we managed to `rake cli:install` locally with Xcode 8 in the first place?

I guess we should change [this line](https://github.com/SwiftGen/SwiftGen/blob/master/rakelib/utils.rake#L125) to use `9.*` now if we do require Xcode 9. Or try Xcode 9 and fallback to Xcode 8 in case SwiftGen is still indeed able to build in Xcode 8.
But I'm confused then how does that manage to build SwiftGenKit which require Xcode 9, right? Or do we only need Xcode 9 to run the unit tests for templates (for testing the output of Swift 4 templates), but not when we just build?

**Comment by djbe** [comment]
The Homebrew issue was with Xcode 8.2 and 8.3 (the latter needed for some new foundation stuff).
Only the templates require Xcode 9, and only for compiling the output files.

So no, we don't require Xcode 9 for compilation. Not sure how to adapt the rake function to check `8.3` or above?

**Comment by AliSoftware** [comment]
We can search for `9.*` and if not found search for `8.*`
Or we can remove the `kMDVersionItem` part from the spotlight query to get all versions, and do the sort of the list of found Xcodes as we already do, and once sorted and extracting the highest version, do a last check to ensure the version is >8 at a last step.

Something like:
```ruby
def self.version_select
    MIN_VERSION = 8.0
    xcodes = `mdfind "kMDItemCFBundleIdentifier = 'com.apple.dt.Xcode'"`.chomp.split("\n")
    
    # Order by version, get the latest one
    xcodes.map { |path| { :vers => `mdls -name kMDItemVersion -raw "#{path}"`, :path => path } }
    latest_xcode = xcodes.sort { |p1, p2| p1[:vers] <=> p2[:vers] }.last

    # Check if it's at least the right version
    unless latest_xcode[:vers].to_f >= MIN_VERSION
      raise "\n[!!!] SwiftGen requires Xcode #{MIN_VERSION}, but we were not able to find it. If it's already installed update your Spotlight index with 'mdimport /Applications/Xcode*'\n\n"
    end

    %Q(DEVELOPER_DIR="#{latest_xcode[:path]}/Contents/Developer")
  end
```
I'm not completely sure about the `latest_xcode[:vers].to_f >= MIN_VERSION` test, will have to check against tricky cases like `9.1.beta.6`, but you get the idea.

**Comment by djbe** [comment]
Sounds good to me if it works 😄 
The more code we put in there though, the more we might want to cache the result of this function?

**Comment by AliSoftware** [comment]
`@version_select ||=` would be a good pattern to use there indeed

**Comment by AliSoftware** [comment]
Another question we could ask is, do we want to force the version used even if the currently `xcode-select -p`'d version already fulfill the requirements?

```ruby
current_xcode = Pathname.new(`xcode-select -p`).parent.parent
current_xcode_version = `mdls -name kMDItemVersion -raw #{current_xcode}`.chomp
return "" if current_xcode_version.to_f >= MIN_VERSION # if already fulfill min version don't force DEVELOPER_DIR=…
…
```

**Comment by djbe** [comment]
So that check would go before the rest? (kind of a guard statement)

**Comment by AliSoftware** [comment]
exactly

**Comment by txaiwieser** [comment]
Cannot install via homebrew on macOS 10.13. Is it the same issue?


`Txais-MacBook-Pro:Warren-iOS txaiwieser$ brew install swiftgen
==> Cloning https://github.com/SwiftGen/SwiftGen.git
Updating /Users/txaiwieser/Library/Caches/Homebrew/swiftgen--git
==> Checking out tag 5.1.1
==> gem install bundler
==> bundle install
==> bundle exec rake cli:install[/usr/local/Cellar/swiftgen/5.1.1/bin,/usr/local/Cellar/swiftgen/5.1.1/lib,/usr/local/Cellar/swiftgen/5.1.1/share/swiftgen/templates]
Last 15 lines from /Users/txaiwieser/Library/Logs/Homebrew/swiftgen/03.bundle:
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/private/tmp/swiftgen-20170921-9006-rjtu5p/gem_home/bin/bundle:22:in `load'
/private/tmp/swiftgen-20170921-9006-rjtu5p/gem_home/bin/bundle:22:in `<main>'
Tasks: TOP => cli:install => cli:build
(See full trace by running task with --trace)

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Formulae without Sierra bottles https://github.com/Homebrew/homebrew-core/issues/6408
hadoop 2.8.1 failed to install on 10.12.6 https://github.com/Homebrew/homebrew-core/issues/17065

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.`

**Comment by djbe** [comment]
Weird, it's annoying we can't see what the error actually is.

Could you try following the "Compile from source"  steps and see if those work?

**Comment by fxcoudert** [comment]
Xcode 9 is now released, and will be the version of most users even on macOS 10.12. macOS 10.13 is getting released on Monday. Any chance this is moving forward?

**Comment by djbe** [comment]
I'd love to move this forward, but I actually need input from users on 10.13, as I'm not on it myself (and won't be on release, as this is also my work device).

Has anyone on 10.13 tried the "Compile from source" installation instructions?

**Comment by djbe** [comment]
And I'd like to re-iterate that, if you need SwiftGen on 10.13 right now and HomeBrew isn't working for you, you can always use:
- SwiftGen from the ZIP from the latest release
- Use CocoaPods to install SwiftGen for your project

Both will always use a pre-built binary that should work for you. HomeBrew will fallback to compile from source in certain cases.

**Comment by fxcoudert** [comment]
@djbe I know, I'm a Homebrew maintainer. But we can't build binary packages right now for our users, because they don't build for us (and we don't ship binaries from other sources, only the ones we built from source)

**Comment by djbe** [comment]
Right, now the initial issue you mentioned here (xcode version requirement) should be fixed, as we made changes to our xcode detection code to handle "8 or higher":
https://github.com/SwiftGen/SwiftGen/blob/master/rakelib/utils.rake#L133

**Comment by fxcoudert** [comment]
@djbe sorry, my bad. Could you consider releasing a new version (maybe 5.1.2) so we (Homebrew) can update our formula?

**Comment by djbe** [comment]
Hmmm, that's something only @AliSoftware can do, he's at FrenchKit for the moment. I'll ping him and see if we can create a small release next week.

PS: no need to be sorry, we can't expect you to check our code 😄

**Comment by txaiwieser** [comment]
Great, just waiting this release :)
