### ISSUE TITLE
Docs: How to run your code

### ISSUE THREAD

**Issue by juli1quere** [SwiftGen/SwiftGen#332]
I have contributions in mind for Swiftgen, but I have some issues to set up the project. In fact, it would be great to have a quick explanation on « How to test your modifications locally ». It will allow people with good will (like me) to contribute to the project in an easy way. The main goal would be to offer the shortest path from `I made a modification into the code` to `I ran it locally`. 

[We can inspire from what fastlane does](https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md)

I don’t think Swiftgen needs something as detailed as that. But just `How to run your code ?`.

**Comment by djbe** [comment]
Which part are we talking about?
- Custom templates
- Additions to SwiftGenKit
- Additions to StencilSwiftKit
- New CLI parameters.

The first 3, ok no problem. The last one probably won't ever be needed as we have a system for dynamic parameters.

Important thing is that we're merging the SwiftGenKit, templates and SwiftGen repositories again, so that'll simplify the whole story.

**Comment by juli1quere** [comment]
In my case, I want to add some command / parameters in the `swiftgen` cli (once my tests are done, I'll write an issue with my idea ). 

In fact, we already have this doc, but not where I was expecting to find it. It's on `Installation` of the README. But I was looking in CONTRIBUTING. 

So, I think that a simple link in CONTRIBUTING will fix the issue.

**Comment by AliSoftware** [comment]
Yeah, I agree that we have room for improving the documentation overall, and #326 will help a lot into simplifying the contribution process again (for external contributors but also for us).

Instead of having to explain to potential contributors the complexity of the project (having to open the PRs in various repositories, understanding submodules, etc…), or searching for documentation in the appropriate repository (templates for templates doc, SwiftGenKit for context docs…), having it all back in one monorepo would simplify both the maintenance and the contribution process… and allow us to work on a clearer documentation from there where things will be more clear and straightforward.

I'm also learning from https://github.com/maintainers/discussions where we have interesting discussions about documentation, monorepo vs multirepo, and contributing manifests.

Note that there's already a CONTRIBUTING.md file in SwiftGen (like in many repos, that's a standard) which aims to describe how to contribute and should contain instructions to how to run SwiftGen locally — and [there's actually already a (short) paragraph about that](https://github.com/SwiftGen/SwiftGen/blob/master/CONTRIBUTING.md#building--running), but I agree it could be improved. It's just gonna have to wait for #326 otherwise we'd have to re-write it immediately

**Comment by djbe** [comment]
@juli1quere before you work out a whole system for new cli paramters, we currently have:
- `--param` for providing variables to the contexts in a template
- `--option` will be similar, but for providing (parsing) options to SwiftGenKit

The latter isn't available yet, but most of the code is prepared for adding it when we're ready.

**Comment by AliSoftware** [comment]
@juli1quere should we close this now that it's more clear to you?

**Comment by juli1quere** [comment]
Sure :).
