### ISSUE TITLE
Default name l10n

### ISSUE THREAD

**Issue by gorbat-o** [SwiftGen/SwiftGen#345]
Hello guys,

I wanted to know if there is a solution to change the default name l10n to something else,
Because i read the documentation, but I didn't find the answer :/

thanks

**Comment by AliSoftware** [comment]
Hello @gorbat-o 

This kind of customisation is documented directly in each template's documentation (see [this note in the README](https://github.com/SwiftGen/SwiftGen/blob/master/README.md#templates-bundled-with-swiftgen).

> You can find the documentation for each bundled template [here in the repo](https://github.com/SwiftGen/templates/tree/master/Documentation), with documentation organized as one folder per SwiftGen subcommand, then one MarkDown file per template.
> Each MarkDown file documents the Swift Version it's aimed for, the use case for that template (in which cases you might favor that template over others), **the available --param parameters to customize it on invocation**, and some code examples.

For example [here for the structured-swift3 template for Strings](https://github.com/SwiftGen/templates/blob/master/Documentation/strings/structured-swift3.md) it's explained that you can use `--param enumName=WhatEver`

We'll soon (hopefully) merge back to a monorepo so that the documentation for templates will be at the same place as the documentation for SwiftGen as a whole, making it even more discoverable.

**Comment by gorbat-o** [comment]
Oh ok, i wasn't sure about the meaning of "enumName" 
Thanks,
Have a good day 👍
