### ISSUE TITLE
New version fails to generate sources but exists with code 0

### ISSUE THREAD

**Issue by NachoSoto** [SwiftGen/SwiftGen#346]
_Version: `SwiftGen v5.2.0 (Stencil v0.9.0, StencilSwiftKit v2.3.0, SwiftGenKit v2.1.1)`_

I wasted a good 20 minutes trying to figure out why my build on Travis was failing. Turns out the latest `SwiftGen` stopped generating sources, but I didn't see this locally because the old sources worked, and new ones weren't being generated, despite the build phase **not failing**:

```
Error: You need to choose EITHER a named template OR a template path. Found name 'structured-swift3' and path ''
```

This is my script:
```bash
swiftgen fonts "$FRAMEWORK_DIR/../app/resources/fonts" --output "$OUTPUT_DIR/Fonts.swift" -t swift3
swiftgen colors "$FRAMEWORK_DIR/resources/Colors.clr" --output "$OUTPUT_DIR/Colors.swift" -t swift3
swiftgen strings "$FRAMEWORK_DIR/en.lproj/Localizable.strings" --output "$OUTPUT_DIR/Strings.swift" -t structured-swift3
swiftgen xcassets "$FRAMEWORK_DIR/Assets.xcassets" --output "$OUTPUT_DIR/Images.swift" -t swift3 --param noAllValues
```

I still don't really know why this broke, but either way this error should make `swiftgen` fail instead of continuing silently.

**Comment by NachoSoto** [comment]
I'm really confused about what this error is trying to tell me. The docs in the `README` don't make sense either:

> Note: you should specify one and one template when invoking SwiftGen

**Comment by djbe** [comment]
I think the word `only` is missing there: `one and only one template`.

**Comment by AliSoftware** [comment]
Did you set `set -e` at the beginning of your script?

Because in a shell script, if one command fails, that doesn't make the whole sh script fail but the shell continues to execute the next line in the script. So the exit code of the whole script is only the exit code of the last command.
At least that's the default sh behavior. Setting `set -e` changes that behavior of your shell so it fails at soon as one command in the shell fails.

**Comment by NachoSoto** [comment]
> Did you set set -e at the beginning of your script?

I always do, yes:

<img width="751" alt="screen shot 2017-10-23 at 12 02 58 pm" src="https://user-images.githubusercontent.com/685609/31907917-21658e14-b7ea-11e7-83c2-7d7c5373fb10.png">

**Comment by djbe** [comment]
Could it be there are some spaces after one line?

**Comment by NachoSoto** [comment]
> I think the word only is missing there: one and only one template.

That seems likely. I'm only specifying one template and no path though... so I have no idea what's wrong with these invocations that were working in `5.1.2`.

**Comment by AliSoftware** [comment]
(Also you should switch to a swiftgen.yml now, a shell script is so 5.1 😛)

**Comment by NachoSoto** [comment]
@AliSoftware maybe I will at some point or for another project. Right now I just want to get this to work again, as this minor version bump has completely broken our project...

**Comment by djbe** [comment]
Do you know which one is the failing line?

**Comment by NachoSoto** [comment]
All of them are failing:
<img width="678" alt="screen shot 2017-10-23 at 12 07 51 pm" src="https://user-images.githubusercontent.com/685609/31908149-cf507fde-b7ea-11e7-99d4-7aeb61441f9d.png">

**Comment by NachoSoto** [comment]
Looks like the bug is that `SwiftGen` is using the path `''` as the default, instead of no path?

**Comment by NachoSoto** [comment]
Yup, here it is: https://github.com/SwiftGen/SwiftGen/blob/master/Sources/Commander/ParserCLICommands.swift#L18

🤦‍♂️

**Comment by NachoSoto** [comment]
So basically both options are defaulting to an empty string, and `SwiftGen` fails if both are set, which means this always fails if only one of them is specified :(

**Comment by djbe** [comment]
Hmmm, I thought I tested this, but probably had the same issue (no `-e` flag).

https://github.com/SwiftGen/SwiftGen/blob/master/Sources/TemplateRef.swift#L22 thinks path can be nil, when it can't. The switch should be checking which of both are `isEmpty`.

**Comment by NachoSoto** [comment]
> but probably had the same issue (no -e flag).

Again, **I do have a `-e` flag**, so there are 2 bugs here:
- Backwards incompatible change to parameters breaks generation.
- Error parsing parameters doesn't result in a non-0 exit code.

**Comment by djbe** [comment]
Right, sorry, wrong wording there.

For the 2nd issue, maybe rethrow all errors we catch in:
https://github.com/SwiftGen/SwiftGen/blob/master/Sources/Commander/ParserCLICommands.swift#L55

**Comment by NachoSoto** [comment]
Is there a workaround for the first one? Homebrew doesn't make it easy to rollback...

**Comment by AliSoftware** [comment]
For the 2nd issue indeed I think our switch to the new `logMessage(.error, …)` system might have changed some behaviours back to "just log the error but don't exit with an exit code", so there might be some places where we forgot to rethrow — while we should have, to make the whole process exit with non-zero code.

@NachoSoto We'll try to do a hotfix ASAP, but in the meantime:

* If you didn't `brew cleanup` yet, you probably still have the old version, so you can switch the brew symlink back to it using `brew switch swiftgen the-old-version-number`
* If you already removed the old version with `brew cleanup`, or for your CI where you probably `brew install` on every VM spawn for each build:
  * you can either download the sources at the previous tag and `rake install[bindir,libdir,tpldir]` — using the proper homebrew folders for bindir, libdir and tpldir to install them where Homebrew would have installed them — but that would mean recompile SwiftGen every time you run a CI job
  * you could download the swiftgen ZIP from the GitHub release you're interested into, and use that instead (if your project build phase relies on SwiftGen being installed system-wide you could just unzip the zip where Homebrew would have installed it, or actually anywhere you like, then do a symlink to the binary in `/usr/local/bin` to be callable system-wide, I guess that could work too.

Otherwise, just wait for the next release, I'll try to make one as soon as those two issues have been fixed.

**Comment by AliSoftware** [comment]
@djbe What puzzles me is that when I look at the code before my PR changing swiftgen.yml and the log system, we already had `printError(…)` instead of `logMessage(.error, …)` but no `rethrow`.

So maybe even in old versions, those errors never never exited with a non-zero exit code and we already had that bug even before my PR? But nobody never realised it before?

**Comment by AliSoftware** [comment]
Can we close this now that both PRs are merged?

**Comment by djbe** [comment]
I assume so.

**Comment by AliSoftware** [comment]
5.2.1 released, fixing the issue (hopefully)!

* in CocoaPods:

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SwiftGen (5.2.1) successfully published
 📅  October 24th, 14:48
 🌎  https://cocoapods.org/pods/SwiftGen
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

* in [GitHub Releases (ZIP)](https://github.com/SwiftGen/SwiftGen/releases/tag/5.2.1)
* in Homebrew: release [pending](https://github.com/Homebrew/homebrew-core/pull/19795)

**Comment by NachoSoto** [comment]
Thank you so much @djbe @AliSoftware! Everything's working again <3

**Comment by djbe** [comment]
Glad to hear it 😄
