### ISSUE TITLE
SwiftGen no longer offers enum cases for L10n and Asset

### ISSUE THREAD

**Issue by danielsaidi** [SwiftGen/SwiftGen#358]
Hi!

In an app that uses SwiftGen `3.0.0`, I use

```
$PODS_ROOT/SwiftGen/bin/swiftgen strings -t swift3 ...
```

and 

```
$PODS_ROOT/SwiftGen/bin/swiftgen images -t swift3...
``` 

This generates an `L10n` enum with the following format:

```
import Foundation
   enum L10n {
      case account
   }
}

extension L10n: CustomStringConvertible {
   var description: String { return self.string }

   var string: String {
      switch self {
         case .account:
            return L10n.tr(key: "Account")
         }
      }
}
```

and for an Asset enum with the following format:

```
#if os(iOS) || os(tvOS) || os(watchOS)
import UIKit.UIImage
typealias Image = UIImage
#elseif os(OSX)
import AppKit.NSImage
typealias Image = NSImage
#endif

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum Asset: String {
   case actionsheetAbc = "actionsheet_abc"
}

extension Image {
   convenience init!(asset: Asset) {
      self.init(named: asset.rawValue)
   }
}
```

I love this, since I can pass around L10n and Asset values, instead of strings and images.

However, when I bump to `5.2.0`, the generated output becomes strings and images, regardless of which template I use.

Are the above templates still available in some way in `5.2.0`, or do I have to build custom ones?

**Comment by AliSoftware** [comment]
Hi @danielsaidi 

We discussed that when we made the templates evolve in the dedicated repo. We saw that having to call `.image` or `.string` on the constants annoyed most people, and since some other templates already used the direct value for the constant instead of wrapping them, we decided to drop the wrappers and point the constants to the values directly.

This change is also a consequence of templates now having the ability to be recursive / hierarchical, e.g. if you organise your asset catalog content into folders and subfolders, we'll create the same hierarchy in the constants. That means that there's no unique type to represent an asset anymore (like `enum Asset: String` was), because now if you have a folder "Fruits" and a folder "Cities" in your asset catalog, you'll have `enum Fruits` and `enum Cities` instead of a single type matching all your templates.

So to answer your question, it's still possible to make the constants be instances of a given type (or at least of a given protocol, to which all the types at the different hierarchical levels will have to conform to), but you'll have to write that template yourself, as we don't include that approach into SwiftGen anymore to avoid the need to use the additional indirection at call site.

_Note: If you feel that the template can still be useful to other people, we could consider a PR to add it to the rest of the bundled templates in a later version, bug given we're in the process of migrating the repos back into a monorepo, it's best to wait for that monorepo-merge first before submitting any new PR_

**Comment by danielsaidi** [comment]
Thanks for the quick reply! 

Sad to hear that. We have forced the use of L10n and Asset in our app to ensure that developers always use the generated cases, since it assures that all UI strings are localized and all assets are generated from the asset catalog. Allowing UIImage and String makes it possible to use "invalid" values.

I will look into generating these templates of my own.

Thanks again!

**Comment by AliSoftware** [comment]
I think it can be quite straightforward actually to migrate to something similar to what you seek, not with `cases` (because that would need to generate `switch` for all images as images can't be associated to cases as raw values, and because you seem to want a unique common type for all the images regardless of the hierarchical level they're in inside your asset catalog, so regardless of the `enum` they're listed into), but rather using a dedicated `struct` wrapper type.

```swift
struct ImageAsset {
  private let image: UIImage
  init(name: String) { self.image = image }
}

// Then generated enums by SwiftGen could look like this:
enum Assets {
  enum Fruits {
    static let apple = ImageAsset(…)
    static let banana = ImageAsset(…)
  }
  enum Cities {
    static let newYork = ImageAsset(…)
    static let cupertino = ImageAsset(…)
  }
}
```

That would also probably make it easier to build rather than making the `enum` having `case` with a bit `switch` to provide the `UIImage` based on the case if you want it to also be generic and compatible with iOS/tvOS/watchOS/macOS all at once without duplicating code in each `switch's cases`…

**Comment by djbe** [comment]
I'd like to note that this discussion only applies to the output of the `strings` command, not for `xcassets`. The latter returns an `ImageAsset` type, on which you have to call `.image` to get the actual image object.

For the strings output, you could apply the same concept, namely to have the constants return an intermediary struct, on which you call something like `.translated` to get the translation.

**Comment by AliSoftware** [comment]
Oh, good point @djbe 👍 . I thought we migrated to direct constants for assets too, which the original issue example suggested too, but I now remember that we didn't (also because `UIImage`s aren't guaranteed to be lazy-loaded I think?).
So we already do the trick I explained above for image assets, you'd just have to apply the same idea to your Strings template.

**Comment by danielsaidi** [comment]
Thanks for your input, really appreciate it! I will have a look at this later on, and perhaps convert my code to not use the enums that SwiftGen 3 generated...but I still really like how these enums enforce using the generated output, which can't be manually created and thus wrong.

**Comment by djbe** [comment]
As mentioned, for assets you can just require your developers to provide `ImageAsset`s.

For strings, we could consider adding a variation to the template, and a PR is always welcome. But keep in mind that we would only accept such changes if they make sense for all users, not a very small subset of them.

**Comment by danielsaidi** [comment]
Even if I still think that the old L10n enum was nice, I have started using the new string properties instead. I'll close this issue to save you some open issue list space :)

**Comment by danielsaidi** [comment]
@Sajjon Hi friend! :)

I basically just threw away the L10n type dependency and just use the string values from now on. It's a lot simpler this way, although I liked the "type safety" of using L10n parameters instead of strings. Now, we just have to find some time to remove all these L10n parameters :)

The typealias approach above looks interesting, but it seems like it can be over engineered ;)
