### ISSUE TITLE
Option to use 4 spaces instead of 2

### ISSUE THREAD

**Issue by BalestraPatrick** [SwiftGen/SwiftGen#390]
Hey there! Great tool first of all.

I noticed that the generated code is always indented with 2 spaces due to the fact in how the `.stencil` templates are written. Is there any option to switch to 4 spaces for example?

Thanks!

**Comment by AliSoftware** [comment]
Hi @BalestraPatrick !

Currently the way we have the templates written, there is no option to do that.

That's something that's technically doable, by adapting the templates so they could take a `--param spaces 4` or something to customize this.
However, that would mean duplicating the unit tests fixtures/outputs just to test for that parameter and extra maintenance for a benefit that I don't see, since this is generated code anyway, so not like source files you'll have to manipulate and write into and want conventions like that at all cost.  

I mean, I understand the request and will to have that, but that kind of parameter, but starting to go that way would mean that we should also give the option to have tabs instead of spaces too, but also give the option to write the `guard let` we generate be on one line instead of multiple, or options to go to the next line after every parameter of a function call… or any other fancy convention people prefer to use. That would make the templates begin to be unmaintainable and quite complex.

The solution that I suggest is:

* Either don't care for tabs vs spaces & 2 spaces vs 4 spaces in generated code (I generally encourage to exclude the generated files from any linter like using the `excluded: Constants/` key in `.swiftlint.yml`, same idea for SwiftFormat, etc)
* Or if you really want to change the spacing for the generated code, it's quite simple actually, you just have to customize the template you use for the generated code, [like explained here in the documentation](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Creating-your-templates.md#printing-a-template-creating-a-new-template).

It's a simple matter of duplicating an official template, customize it to change the indentation used in those templates, and then point to that customised template in your `swiftgen.yml` (or change the `-t` to a `-p` if you're still using parameters passed to the command line)

**Comment by BalestraPatrick** [comment]
Thanks for the fast response @AliSoftware! Yes, I definitely agree in not including this improvement as part of the library since it's all generated code and it'd clutter the `SwiftGen` codebase. 
I didn't think about duplicating the template and modify them to my needs, so I think I will do that if I really need this feature.

Thanks 💯

**Comment by AliSoftware** [comment]
That's the whole point of having SwiftGen being template-based, so that everyone can customize it to their needs 😉
