### ISSUE TITLE
Flat-template for xcassets swift4

### ISSUE THREAD

**Issue by landsv** [SwiftGen/SwiftGen#407]
Is there a way to use the old flat template with swift 4? Because for not we have around 300 errors to fix... =(

**Comment by djbe** [comment]
Note: there never was a flat template for Swift 4, only for Swift 2 and 3.

You could try using an old version of the template for Swift 3, last one I can find is here:
https://github.com/SwiftGen/templates/blob/1.1.0/templates/images-swift3.stencil
And updating it for all the context changes that have happened since then. Docs for the asset catalog context can be found here:
https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/SwiftGenKit%20Contexts/Assets.md

Although I think it might be easier to just modify the dot-syntax template (the current one) to a flat version. Or just install an older version of SwiftGen if this is for an urgent task. Dot-syntax templates have been the default since SwiftGen 5.0 (see our migration guide: https://github.com/SwiftGen/templates/blob/master/Documentation/MigrationGuide.md#deprecated-templates-in-20-swiftgen-50)
