### ISSUE TITLE
Use swiftlint:disable all

### ISSUE THREAD

**Issue by fredpi** [SwiftGen/SwiftGen#409]
SwiftGen Version: 5.3.0
Xcode Version: 9.3

I suggest using `// swiftlint:disable all` for all files generated by SwiftGen instead of single `disable` commands:

```
// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length
```

The option to do this is first introduced in SwiftLint 0.25.1 and allows for also ignoring custom, user-defined rules in SwiftGen-generated files. Previously, the user had to manually exclude SwiftGen files, if they had created a custom rule not being respected by SwiftGen.

**Comment by djbe** [comment]
Actually we generally suggest users ignore all generated files for linting, as we can't predict (like you said) what rules will be active, or if any new rules are being used.

For now we still only disable what's necessary to ensure we're writing decent & correct code.

**Comment by AliSoftware** [comment]
As David mentioned, the thing is we currently do lint the generated code ourselves (there's a lint phase in SwiftGen's project itself, both for SwiftGen's own code but also for the fixtures it tests), to ensure that the templates we provide generate consistently-styled code. And for example catch a violation in case our template is done in such a way that it would miss adding a space after a `:` at some place in the generated code.

Sure, code generated by SwiftGen is _generated_ so not intended to be modified by humans. Still it can be conceived as being intended to be _read_ by humans, and as such we want it to be consistent and follow at least our code-styling.

I see the point in excluding Code-Generated code from SwiftLint, and in fact indeed we suggest our users to put the files generated by any code-gen tool like SwiftGen or Sourcery in the exceptions of SwiftLint. In that regard, using `swiftlint:disable all` would make sense. But I'd also still want to be able to ensure, via some kind of unit test in SwiftGen, that the templates we provide generate code that is consistent code-style-wise — which is why we currently lint it today as part of a Build Phase of SwiftGen and of one of our CI step too…

**Comment by fredpi** [comment]
@AliSoftware I get your point here.

Without having taken an in-depth-look at the codebase, one suggestion possibly solving both issues would be to include `// swiftlint:disable all` on top of each generated file by default, despite if a configuration entry is found disabling this explicitly. For the project itself, one could add such a configuration entry, while `// swiftlint:disable all` would be included for files generated in user projects where no such entry is included in the config file.

**Comment by AliSoftware** [comment]
That's an interesting solution indeed
