### ISSUE TITLE
Swiftgen install is broken via Homebrew

### ISSUE THREAD

**Issue by vincedev** [SwiftGen/SwiftGen#430]
Tried to upgrade Swiftgen via Homebrew, to no avail.
Here's what is output :

```
$ brew upgrade swiftgen
==> Upgrading 1 outdated package, with result:
swiftgen 5.3.0
==> Upgrading swiftgen
==> Using the sandbox
==> Cloning https://github.com/SwiftGen/SwiftGen.git
Updating /Users/vince/Library/Caches/Homebrew/swiftgen--git
==> Checking out tag 5.3.0
Error: 5.3.0 tag should be 73ac0e487dda941eb4e52ed3b96b652515f1bee5
but is actually c2b03152f31e779f1deba3811b158ac1670f5b3b
```

Also tried removing/reinstalling completely, same issue.

**Comment by AliSoftware** [comment]
Hello @vincedev 

That's probably because your local homebrew cache has been updated with an invalid tag, or the tag as moved since your last update of the homebrew cache (I remember I had to move the 5.3.0 cache when I submitted to homebrew, because of a last minute mistake I saw specific to the homebrew install, that's probably when you caught the wrong tag before I finally moved it)

To fix your issue, I suggest you cleanup your homebrew cache.

1. You could try `brew cleanup swiftgen` first. That should cleanup any old cache of uninstalled versions of swiftgen on your machine, so that the next time you try `brew upgrade swiftgen` it should re-download SwiftGen from the net and not use your cache.

2. If that doesn't work (`brew cleanup` only cleans cache of uninstalled versions, so maybe it will skip cleaning the cache of swiftgen if you have it installed?), you could co one step further and run `rm -rf $(brew --cache swiftgen)` to completely remove the directory where homebrew stores the cache for all swiftgen versions

Once you've cleaned up the cache with one of the above command, you should `brew update` then retry `brew upgrade swiftgen` again.

---

_Note that, aside from trying to fix that homebrew cache issue you have, I'd suggest you to run `brew cleanup` regularly on your machine. This removes cache of old formulae and old versions of tools you previously installed with homebrew but uninstalled or updated since. That could free you some unused disk space (sometimes up to hundreds of MB), which is always welcome_ :wink:

**Comment by vincedev** [comment]
Hello @AliSoftware , thank you for the quick reply.
So I tried almost everything but still getting the same issue. 
Cleaning entirely SwiftGen related cache indeed makes brew re-clone the repo from GitHub, but it persists to see different commits for the 5.3.0 tag :

```
$ brew --cache swiftgen
/Users/vince/Library/Caches/Homebrew/swiftgen--git
$ brew cleanup swiftgen
$ brew uninstall --force swiftgen
$ brew update
Already up-to-date.
$ brew upgrade swiftgen
Error: swiftgen not installed
$ brew install swiftgen
==> Using the sandbox
==> Cloning https://github.com/SwiftGen/SwiftGen.git
Cloning into '/Users/vince/Library/Caches/Homebrew/swiftgen--git'...
remote: Counting objects: 657, done.
remote: Compressing objects: 100% (457/457), done.
remote: Total 657 (delta 211), reused 444 (delta 173), pack-reused 0
Receiving objects: 100% (657/657), 3.31 MiB | 4.81 MiB/s, done.
Resolving deltas: 100% (211/211), done.
Note: checking out 'c2b03152f31e779f1deba3811b158ac1670f5b3b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag 5.3.0
Error: 5.3.0 tag should be 73ac0e487dda941eb4e52ed3b96b652515f1bee5
but is actually c2b03152f31e779f1deba3811b158ac1670f5b3b
```

**Comment by AliSoftware** [comment]
Ah. damn. It seems that indeed there's a mismatch, as `5.3.0` tag is indeed currently pointing to c2b03152f31e779f1deba3811b158ac1670f5b3b (as seen in Releases tab on GitHub) while the formula (as seen locally on my mac via `brew cat swiftgen`) is indeed still pointing to 73ac0e487dda941eb4e52ed3b96b652515f1bee5 . Maybe tag has moved for some reason since I published on homebrew?… 🤔 

I'm at work rn so won't be able to update the formula right away. I'll have to patch it, hopefully this evening. That will require the homebrew team to then validate my PR to update the formula, so depending on their availability that might take more or less time, I'll let you know.

**Comment by vincedev** [comment]
Alright :)

**Comment by vincedev** [comment]
Woups.. missed your last post.
Yup I confirm it's fixed ! I successfully installed SiwftGen 5.3.0 via Homebrew.

Thank you :)

**Comment by AliSoftware** [comment]
Cool!
Thanks for reporting the issue and for the follow up 👍

**Comment by markiianp-sysmetica** [comment]
I tried all the commands that were here, none is working for me, maybe someone could help

% brew install swiftgen
Error: swiftgen has been disabled because it does not build!
