### ISSUE TITLE
Incorrect case with strings generation

### ISSUE THREAD

**Issue by tdimeco** [SwiftGen/SwiftGen#447]
Hi,

I am working on projects where localisation keys are CamelCase, like:

```swift
"MySuperKey.title" = "Translation";
```

SwiftGen (using the `structured-swift4` template) generates intermediate enums using the wrong case:

```swift
internal enum L10n {
    internal enum Mysuperkey { // Should be named MySuperKey
        internal static let title = L10n.tr("Localizable", "MySuperKey.title")
    }
}
```

The `Mysuperkey ` enum would be named `MySuperKey `. I guess this is an issue.

Thanks!

Thomas

**Comment by AliSoftware** [comment]
Hi.

I think if you don't want that behaviour, you can simply use a custom template (see documentation for creating your custom template, it just consists of duplicating the existing ones and modify them to your likings) to remove the filter changing the case of keys.

**Comment by djbe** [comment]
Hi Thomas,

This issue is a dupe of #257, where there was a quite long discussion about this issue. At the end of it the OP even provided a script to address some stuff. The issue was also addressed in this PR: #398.

Like @AliSoftware mentioned, if the casing in the build-in templates doesn't work for you, you can always use a custom template.

Note: as this issue has been extensively covered before in other tickets, I'm going to close this ticket in a day or 2 unless the above comments don't address your issue.

**Comment by tdimeco** [comment]
@AliSoftware That's true. Now, the question is to know if it's the desired default behaviour or not. ;)

**Comment by tdimeco** [comment]
Ok, thanks. I now understand why SwiftGen do it this way. Indeed it's "hard" to solve without compromises.

I can close this issue. Have a good day.

**Comment by djbe** [comment]
To clarify: it's our intention to eventually have only 2 behaviours for strings: don't modify the keys **at all**, or prettify them a bit (for keys like `my.string.hello-world`).
