### ISSUE TITLE
Improvement: Support for NSManagedObject Properties

### ISSUE THREAD

**Issue by ghost** [SwiftGen/SwiftGen#45]
You can add NSManagedObject's attributes and relationships as strings. It would help typo mistakes while using in NSFetchRequests and other CoreData Methods.

**Comment by AliSoftware** [comment]
Great idea! :+1: 

Don't hesitate to make a PR to create a DataModelParser that could do that :wink:

**Comment by AliSoftware** [comment]
If you don't feel confortable creating the code, at least I'd be interested to see what you imagine the generated code be like (you could even for example propose a Stencil template):

* Will it be an `enum` per `NSManagerObject`, with one `case` per attribute?
* Or one `struct` per `NSManagedObject` containing an `enum attributes` with one `case` per attribute, and an `enum relationships` with one `case` per relationship?
* Will it be useful to generate an `enum` for other properties as well, like its nullability, its type, etc?
* Will it be useful to generate some `static var myAttribute: String` (if the `myAttribute` is of type `String`) for each attribute ?

Would be very interested in your feedback (especially since it has been some time I haven't used CoreData, as for my latest projects I'm more used to play with Realm instead, so I've probably lost my touch on that)

**Comment by mehulmind123** [comment]
Consider use of following property when creating NSFetchRequest where we have to pass attributes names as strings in array. So I think enum per NSManagedObject with one case per attribute/relationship will be fine.
@property (nonatomic, copy) NSArray *propertiesToFetch NS_AVAILABLE(10_6, 3_0);

**Comment by djbe** [comment]
#455 has been merged, which implements this feature. I'd like to thank everyone who participated in this issue and the PRs leading up to this.

We'll probably do a release this weekend. In the meantime, people who'd like to try this feature can check out the develop branch,
