### ISSUE TITLE
HomeBrew: Compile from source error

### ISSUE THREAD

**Issue by jsonfellin** [SwiftGen/SwiftGen#458]
I'm getting an error with run `brew install swiftgen --HEAD`:
```
Error: No such file or directory - Tests/Fixtures/Resources/Storyboards-iOS
```
Really want to make use of this PR: https://github.com/SwiftGen/SwiftGen/pull/396. Any help would be greatly appreciated!

**Comment by djbe** [comment]
Right, this is because the directory structure changed (again 😆 ).

You don't need to install SwiftGen from source to be able to use that fix. You can just get the latest fonts template here:
https://github.com/SwiftGen/SwiftGen/blob/master/templates/fonts/swift4.stencil
And point your configuration to use that as a custom template for now (until 6.0 is released).

**Comment by djbe** [comment]
@AliSoftware we'll have to update the brew file again :trollface:

**Comment by AliSoftware** [comment]
SwiftGen 6.0.0 (with fixed formula) will finally be available in homebrew as soon as this PR is merged by the Hombrew team: https://github.com/Homebrew/homebrew-core/pull/32545 🎉
