### ISSUE TITLE
SceneType swift4 template Any can be UIViewController when targeting iOS

### ISSUE THREAD

**Issue by darronschall** [SwiftGen/SwiftGen#463]
When targeting iOS using SwiftGen 5.3.0 and swift4 storyboard template, SceneType generates as:

```
internal struct SceneType<T: Any> {
  internal let storyboard: StoryboardType.Type
  internal let identifier: String

  internal func instantiate() -> T {
    let identifier = self.identifier
    guard let controller = storyboard.storyboard.instantiateViewController(withIdentifier: identifier) as? T else {
      fatalError("ViewController '\(identifier)' is not of the expected class \(T.self).")
    }
    return controller
  }
}
```

Rather than `Any`, these can be typed as `UIViewController` since the call to `instantiateViewController` can only return a `UIViewController` in UIKit: https://developer.apple.com/documentation/uikit/uistoryboard/1616214-instantiateviewcontroller

This only applies to iOS; AppKit's corresponding instantiateController still returns `Any`:  https://developer.apple.com/documentation/appkit/nsstoryboard/1426549-instantiatecontroller

(I'm happy to submit a PR to modify the template for this if you'd like me to)

**Comment by AliSoftware** [comment]
That's a good point! We'd welcome a PR indeed :+1:

---

Just for the story: I can't really remember why we made that return `Any`, but I guess it's probably because of the inconsistency between iOS and macOS you pointed out.

And since SwiftGen ends up generating `SceneType<…>` with a `T` that's indeed always a `UIViewController` subclass, and that `SceneType` isn't intended to be instantiated by your code (the only `SceneType<X>.init` that you'll see should be the ones generated by SwiftGen and not ones in your own hand-typed code, at least that's not intended to), then we didn't bother much to refine that constraint on `T` to anything other than `Any`

_(The fact that we explicitly put `<T: Any>` instead of just `<T>` makes me believe that even if I don't remember it, this explanation seems the most plausible one, probably because we had `<T: UIViewController>` before we started supporting macOS, then when we added macOS support we just changed `UIViewController` to `Any` instead of removing the constraint altogether, I guess…)_

---

That being said, that would indeed be more exact to have `SceneType<T: UIViewController>`. Even for macOS/AppKit, if `instantiateViewController` (strangely) returns `Any` instead of `NSViewController`, we'll `as? T` the result anyway… so better make that constraint right as you suggested :wink:
