### ISSUE TITLE
Strings: Parameter to change `NSLocalizationString` usage with custom mechanism

### ISSUE THREAD

**Issue by LeonidKokhnovich** [SwiftGen/SwiftGen#468]
Hi! I see that by default for localized strings we get this extension:
```
extension L10n {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, tableName: table, bundle: Bundle(for: BundleToken.self), comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}
```
It would be really nice if there was a way to customize like:
```
extension L10n {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let format = myCustomFunction(key, tableName: table, bundle: Bundle(for: BundleToken.self), comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}
```
On one of the projects we use plist with XML strings instead and it doesn't work with NSLocalizedString, but we have a custom getter to get the string by the key.

**Comment by AliSoftware** [comment]
Hi,

you can already do that yourself :wink: Simply create a custom template (see [the dedicated documentation](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Creating-your-templates.md#printing-a-template-creating-a-new-template), it's just a matter of duplicating one of the templates bundled with SwiftGen and modify just the line you need) and then configure your `swiftgen.yml` to use this template instead of one of the bundled ones.

This seems to be a quite specific need for your `myCustomFunction`, so I don't thing it would be worth it for us to include that in the default templates bundled in SwiftGen. But that's why SwiftGen is so configurable with custom templates and all after all :wink: so you can customize that yourself without the need to wait for a new release of SwiftGen or whatever.

**Comment by djbe** [comment]
The bundled templates in 6.2 have a `lookupFunction` parameter which, if set, ensure that the generated code does not work with `let` constants and fetches the translated string on each get access.

See here for an example of generated code: https://github.com/SwiftGen/SwiftGen/blob/stable/Tests/Fixtures/Generated/Strings/structured-swift5/localizable-lookupFunction.swift
And check the template docs here: https://github.com/SwiftGen/SwiftGen/tree/stable/Documentation/templates/strings
