### ISSUE TITLE
Tests: Xcode 10 issues

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#486]
Some of these are due to randomised hash seeds, which causes our tests to *sometimes* fail (😭).

- Json/Plist/YAML templates: iteration over dictionary key/values isn't consistent anymore. I think this should be fixed in Stencil itself: the iterator should maybe iterate over the `keys.sorted`. Or do we want to handle this template-side, with some `sort` filter?
- Float string serialisation has changed: `150.0/255.0` outputs `0.5882353` instead of `0.588235`. Internally Stencil calls `(... as CustomStringConvertible).description`, so it's something we can't really control.

**Comment by AliSoftware** [comment]
Yeah I agree, I think since it's common to iterate over entries of a dictionary in Stencil, and that people will always want deterministic code generated by the template engine, this is not even limited to SwiftGen but should be implemented directly in Stencil iterating over the `keys.sorted` internally.

For the Float string serialisation, I'm not sure that matter. Sure, this will be a problem in our tests during the transition from Xcode 9 to Xcode 10, as depending if you run the tests with one or the other, the result will be slightly different, but once Xcode 10 GM is out (less than a month I guess?) and we'll have fully migrated to Xcode 10 (both on our dev machines and on CI), that problem will go away, so I don't think we should go into too much length to try and make it have the same output between 9 and 10, given it might be complex to unify that for a benefit that will disappear in a month or two.

**Comment by djbe** [comment]
Closed by #498 and #504.
