### ISSUE TITLE
SwiftGen 6.0

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#499]
Waiting on:
- [x]  #484 (migration guide)
- [x] https://github.com/stencilproject/Stencil/issues/251: a Stencil release, because 0.12 has a bad performance issue.

Todo:
- [x] Update Stencil (see above)
- [x] Maybe merge #498 (xcode 10/swift 4.2) 
- [x] Update podspec
- [x] ⚠️ Update the brew formula (some paths have changed again)
- ...
- Profit!

**Comment by yonaskolb** [comment]
So a new release is out soon then? Hanging out for the yaml generation 🎉😄

**Comment by djbe** [comment]
@yonaskolb After #511 is done, we can release 6.0.

You can always build and test a version of master (see the installation instructions). The YAML generation changed quite a bit since the initial implementation, so it'd be great if you could check it out before release.

**Comment by AliSoftware** [comment]
@yonaskolb yes, it's already in the works in https://github.com/SwiftGen/SwiftGen/pull/509, hoping to do it this weekend!

Don't hesitate to help us review the last bits of documentation in #511 ;-)

**Comment by AliSoftware** [comment]
Damn, posted 5 seconds late 😅

**Comment by fxcoudert** [comment]
We'll be happy to get a pull request for the new release in Homebrew :)

**Comment by fxcoudert** [comment]
```
==> bundle exec rake cli:install[/usr/local/Cellar/swiftgen/5.3.0/bin,/usr/local/Cellar/swiftgen/5.3.0/lib,/usr/local/Cellar/swiftgen/5.3.0/share/swiftgen/templates]
== Building Binary ==
rake aborted!

[!!!] SwiftGen requires Xcode ~> 9.2, but we were not able to find it. If it's already installed, either `xcode-select -s` to it, or update your Spotlight index with 'mdimport /Applications/Xcode*'

/private/tmp/swiftgen-20180928-80051-1p3e6r5/rakelib/utils.rake:154:in `compute_developer_dir'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/rakelib/utils.rake:129:in `version_select'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/rakelib/utils.rake:22:in `block in run'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/rakelib/utils.rake:22:in `map'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/rakelib/utils.rake:22:in `run'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/Rakefile:199:in `block (2 levels) in <top (required)>'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/bin/bundle:22:in `load'
/private/tmp/swiftgen-20180928-80051-1p3e6r5/gem_home/bin/bundle:22:in `<main>'
Tasks: TOP => cli:install => cli:build
(See full trace by running task with --trace)
```

**Comment by AliSoftware** [comment]
Ah, right, cool. We already updated the project to build with Xcode 10, so once we update the formula accordingly too we should already be good to go then, 👍

**Comment by AliSoftware** [comment]
@fxcoudert We're in the process or releasing, and while testing our updated formula, we have a strange error — for which we found the solution, but still disturbing
, 
In our formula, we updated to use Xcode 10:

```ruby
depends_on :xcode => ["10.0", :build]
```

My machine is running macOS 10.13.6, With CLT, Xcode 9.4 and Xcode 10 all installed.
I tested the formula via `brew upgrade swiftgen`, but what I didn't realised is that `Xcode-select` was pointing on my Xcode 9.4. And as a result, I ended up with this error:

```sh
Warning: Bottle installation failed: building from source.
swiftgen: A full installation of Xcode.app 10.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode 10.0 cannot be installed on macOS 10.13.
You must upgrade your version of macOS.
Error: swiftgen: An unsatisfied requirement failed this build.
```

If I `sudo xcode-select -s` to my Xcode 10, that error disappears (and I have another one further, but I'm still investigating, might be unrelated) and homebrew starts building my formula.

Isn't that strange that homebrew tells me that I need to upgrade my version of macOS?!

**Comment by wolfe719** [comment]
The rake.utils needs to change to look for a one or two digit XCode major version number. That is why the formula is failing. It is finding "0." instead of "10." - here is the diff:

diff --git rakelib/utils.rake rakelib/utils.rake
index cc2f27e..1e26fd0 100644
--- rakelib/utils.rake
+++ rakelib/utils.rake
@@ -143,7 +143,7 @@ class Utils
     version_req = Gem::Requirement.new("~> #{version_req}") if version_req.is_a?(Float)
     version_req = Gem::Requirement.new(version_req) unless version_req.is_a?(Gem::Requirement)
     # if current Xcode already fulfills min version don't force DEVELOPER_DIR=...
-    current_xcode_version = `xcodebuild -version`.split("\n").first.match(/[0-9.]+/).to_s
+    current_xcode_version = `xcodebuild -version`.split("\n").first.match(/[0-9*.]+/).to_s
     return '' if version_req.satisfied_by? Gem::Version.new(current_xcode_version)
 
     supported_versions = all_xcode_versions.select { |app| version_req.satisfied_by?(app[:vers]) }
-- 

I would do a pull request, but since this thread is already focused on fixing the brew formula...

Sincerely,
John Wolfe

**Comment by AliSoftware** [comment]
Thanks @wolfe719 !

But I'm not sure I'm following:

1. The error I mention above was even before homebrew was trying to build our formula and run our `rake` task. So it's related to the content in the formula itself (`swiftgen.rb` in the homebrew repo), not to `utils.rake` and our `Rakefile` (which, indeed does also perform an Xcode version check
2. `/[0-9*.]+/` doesn't seem like the regex we want. That regex means "find one or more (`+`)  characters that are either a digit (`0-9`), an asterisk `*` or a dot `.`". (In the context of a `[…]` character class, `*` is a literal in regexes).
* And when I start `pry` or `irb` and try to do `%x(xcodebuild -version).split("\n").first.match(/[0-9.]+/).to_s`, so with the current RegEx, while I have Xcode 10.0 `xcode-select`'d, that properly returns `10.0` and not `0.`. Which is expected, since we properly have that `+` in the regex telling us that we search for one digit… or more

Anyway, I think it's still an issue, or bad error reporting, on homebrew, since the error is definitely on the formula's side, even without executing our `Rakefile`…

**Comment by AliSoftware** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SwiftGen (6.0.0) successfully published
 📅  September 29th, 02:14
 🌎  https://cocoapods.org/pods/SwiftGen
 👍  Tell your friends!
--------------------------------------------------------------------------------

(Just waiting for https://github.com/Homebrew/homebrew-core/pull/32545 to be merged for it to be available in homebrew too!)

**Comment by djbe** [comment]
It's available on HomeBrew now 🎉
