### ISSUE TITLE
Duplicates in storyboards

### ISSUE THREAD

**Issue by pikaboo** [SwiftGen/SwiftGen#512]
If I have localized storyboards or have one storyboard referencing another, I  am stuck with uncompilable code "redecleration of variable"

**Comment by djbe** [comment]
Hi @pikaboo,

Could you provide the following:
- The generated swift file
- Your SwiftGen config file, or the CLI invocations you're using
- If possible, the storyboard files you're parsing. If not, maybe a list of the storyboards files?

**Comment by djbe** [comment]
Ah yes, I guessed that'd be the issue. Instead of pointing SwiftGen to `${PROJECT_DIR}/SwiftGen/SupportFiles/Storyboards`, you should point it to `${PROJECT_DIR}/SwiftGen/SupportFiles/Storyboards/Base.lproj`.

Also, you have a bit of a weird directory structure, your `SecondStoryboard.storyboard` seems to be misplaced. It should be in that same `Base.lproj` directory as the other storyboards.

Another thing is that you should use "Localizable Strings" localization for your storyboard files. Your `Launchscreen.storyboard` has an "Interface Builder Storyboard" translation for english, it should be a "Localizable Strings".

**Comment by pikaboo** [comment]
SecondStoryboard.storyboard is not localized

In my project LaunchScreen is localized by UI instead of strings. I.e for english the launch screen is one ui, and for french another, i can't localize it just by strings

**Comment by djbe** [comment]
The launchscreen isn't localizable.

Btw, I actually mean this:
<img width="600" alt="screenshot 2018-09-28 at 00 27 19" src="https://user-images.githubusercontent.com/641356/46178157-faf48c80-c2b5-11e8-882b-46f6263fdc24.png">

Your project structure is quite a bit broken TBH. You have:
- SwiftGen/Base.lproj/SecondStoryboard~.storyboard
- SwiftGen/SupportFiles/Storyboards/Base.lproj/Main.storyboard
- SwiftGen/SupportFiles/Storyboards/Base.lproj/LaunchScreen.storyboard
- SwiftGen/SupportFiles/Storyboards/en.lproj/LaunchScreen.storyboard
- SwiftGen/SupportFiles/Storyboards/SwiftGen/Base.lproj/SecondStoryboard.storyboard

It should be:
- ~~SwiftGen/Base.lproj/SecondStoryboard\~.storyboard~~ delete this
- SwiftGen/SupportFiles/Storyboards/Base.lproj/Main.storyboard
- SwiftGen/SupportFiles/Storyboards/LaunchScreen.storyboard (not localized, so not in Base)
- SwiftGen/SupportFiles/Storyboards/SecondStoryboard.storyboard (not in Base)

Once you get rid of the storyboards with the same name, your problem should solve itself. (keep your swiftgen invocation as you had it).

**Comment by djbe** [comment]
Quote from Apple:
> **Avoid including text on your launch screen.** Because launch screens are static, any displayed text won’t be localized.

**Comment by djbe** [comment]
I'm going to close this, as this is not a SwiftGen issue, but actually more user project issue, and I've outlined the steps to fix this above.
