### ISSUE TITLE
No templates for storyboards.outputs

### ISSUE THREAD

**Issue by RyuX51** [SwiftGen/SwiftGen#525]
The templates for `storyboards.outputs` seems to be missing:

    # swiftgen templates list
    colors:
    ...
    storyboards:
      custom:
      bundled:
    ---

**Comment by AliSoftware** [comment]
Hy @RyuX51 

The `storyboards` command has been renamed `ib`, as explained in the [Migration Guide](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/MigrationGuide.md)

So you should look under the `ib:`  entry to see the list of templates available for the `ib` (previously `storyboards`) command.

The real bug here is that `swiftgen templates list` still lists the `storyboards:` key, while this key has been deprecated and renamed in SwiftGen 6.0 so it shouldn't list it anymore, but should only list the ones in `ib` instead.

_(The cause is probably because we sure deprecated the `storyboards` subcommand, but kept it around for now for compatibility and ease of migration until we remove it completely in the next major release, so our logic in `swiftgen templates list` continues to list a root entry for it, while it should ignore deprecated subcommands in that list)_

**Comment by RyuX51** [comment]
Allright, I just noticed. Thank you and sorry for not reading the migration guide first.

**Comment by AliSoftware** [comment]
No problem, thanks for reporting. There is still a bug to be fixed though, as we should remove that `storyboards:` from the listing anyway.
