### ISSUE TITLE
Strings: Structured strings split by '__' instead of '.'

### ISSUE THREAD

**Issue by brosnic** [SwiftGen/SwiftGen#576]
Hi!

is it possible to split the strings by '__' instead of '.'? 
e.g.: "screen_name__header__title" -> L10n.ScreenName.Header.title

We're trying to use the same keys as our Android peers. They say they can't use dots in the keys...

Thanks!

**Comment by AliSoftware** [comment]
That's currently not possible, but would be a nice addition :+1:

The `SwiftGenKit.Parser` protocol we've defined in SwiftGenKit's source code is [already ready to accept arbitrary parameters to pass to the parser, as seen here](https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGenKit/Parsers/Strings/StringsParser.swift#L35), but there's currently nothing written on SwiftGen (so at the CLI or the config file level) to pass those parameters to the parser. _(not to be confused with parameters passed to the template using `params:` in the config file, as the split happens during the parsing so that parameter would have to be passed to the parser, not the template)_

It would be a great addition to make that possible, so that we could specify a custom separator to the `Strings.Parser` via the configuration file, that would then be used [instead of this one hardcoded here in the parser](https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGenKit/Parsers/Strings/StringsEntry.swift#L35) to split the strings

**Comment by djbe** [comment]
Implemented in #588.
