### ISSUE TITLE
Create a base SwiftGenKit.Parser class to define init() and warningHandler

### ISSUE THREAD

**Issue by jrtibbetts** [SwiftGen/SwiftGen#611]
All of the current implementations of `SwiftGenKit.Parser` have identical initializers and `warningHandler` properties. These can be coalesced into a single `SwiftGenKit.Parser` implementation base class, e.g.

```
public class DefaultParser: NSObject {
  public var warningHandler: Parser.MessageHandler?

  public required init(options: [String: Any] = [:], warningHandler: Parser.MessageHandler? = nil) {
    self.warningHandler = warningHandler
  }
}
```

It should be noted that this base class cannot implement `SwiftGenKit.Parser` _itself_, because it cannot provide any meaningful default `parse(path: Path, relativeTo parent: Path)` implementation. Instead, the various parsers should extend the base class _and_ implement the `SwiftGenKit.Parser` protocol.

**Comment by AliSoftware** [comment]
Hello and thanks for taking the time to write an issue for this suggestion.

I see your point but doing that would mean favor inheritance over composition or protocol conformance. People should be able to make any of their type into a parser, even if they already inherit from some other parent type in their own codebase for example. That's why we use protocols here, to give the maximum flexibility to conformers.

I agree that if there was a lot more implementations shared between all parsers than just the single `init` and `warningHandler`, that might be worth it to provide a default implementation for that (though I'd then probably prefer composition with a default provider, but ¯\\\_(ツ)\_/¯); but given in this case it only provides the `init` means it adds quite little to what we already have.

And last but definitively not least, with the very recent addition of parser options for some of our parsers (see Strings parser for example, but won't be the last), and the way we implemented it so far — with each parser having it's own set of options that would not be common with other parsers, but would have to be properly interpreted in the `init` of each parser differently — having a parent class in those cases wouldn't fit anymore since you'll have to reimplement the `init` for each parser having options anyway…

**Comment by jrtibbetts** [comment]
Thanks for replying so quickly, @AliSoftware! 

> People should be able to make any of their type into a parser, even if they already inherit from some other parent type in their own codebase for example.

I completely agree, and this doesn't affect anyone's ability to do that. This just streamlines the _existing_ parser implementations, even if only by a few lines per file.

> I agree that if there was a lot more implementations shared between all parsers than just the single `init` and `warningHandler`, that might be worth it to provide a default implementation for that (though I'd then probably prefer composition with a default provider, but ¯\_(ツ)_/¯); but given in this case it only provides the `init` means it adds quite little to what we already have.

I agree that it streamlines only a little code, but it's enough code that would be flagged as duplicated by Swiftlint's default settings. However, I think that this is just the first step. All of the parsers that contain an array of parsed options (e.g. `Yaml.Parser`'s `files`) could be genericized with an associated type for the array contents, so that 

```
public class DefaultParser<T>: NSObject {
   var elements: [T] = []
}
```

And if you still wanted to keep the unique names in each `Parser`, that's as simple as adding
```
var files: [T] { return elements }
```

> And last but definitively not least, with the very recent addition of parser options for some of our parsers (see Strings parser for example, but won't be the last), and the way we implemented it so far — with each parser having it's own set of options that would not be common with other parsers, but would have to be properly interpreted in the `init` of each parser differently — having a parent class in those cases wouldn't fit anymore since you'll have to reimplement the `init` for each parser having options anyway…

I noticed that the Strings parser is the only one that's doing anything with the options right now. But if each `Parser` is going to have unique options, they can still call the superclass's `init()` to set up the `warningHandler`.

These are, obviously, just suggestions. I've been using SwiftGen for a while now (thanks!) and wanted to contribute.

**Comment by AliSoftware** [comment]
Thoughts @djbe since you implemented the new type-safe options parsing recently?

**Comment by djbe** [comment]
TBH I prefer the use of mix-ins in this case instead of subclasses.

Swift doesn't have the concept of abstract classes, so this suggestion would at least add a non-sensical empty `DefaultParser`, that we can't mark as "don't use this".

And it's not like there's much repeated code, only 1 or 2 stored properties. All the other common code is already abstracted via the use of mix-ins.

**Comment by jrtibbetts** [comment]
There wouldn’t be any need to mark `DefaultParser` with a “don’t use this” if it’s `internal`. 

I can see several ways that this default implementation can be expanded to handle even more common duties, like maintaining the array of parsed items (as I noted above) and even some option handling.

**Comment by djbe** [comment]
No it can't be declared internal, quick test in playgrounds:
> Class cannot be declared public because its superclass is internal

**Comment by jrtibbetts** [comment]
> No it can't be declared internal, quick test in playgrounds:

Ah, that's true. Hmm.

**Comment by djbe** [comment]
Closing this for now unless there's more input.

While I love reducing code in all places, code correctness matters more. What I want to avoid the most is some sort of base class that "should not" be used, but nothing would prevent it from being used.
