### ISSUE TITLE
Asset Catalog: on macOS images are not loaded from cache

### ISSUE THREAD

**Issue by kodlian** [SwiftGen/SwiftGen#648]
The swift4 template uses `bundle.image(forResource: )` to load images from any bundle. However this method does not cache the image contrary to `NSImage(named: )`. This can slow down the UI if we load images from disk for each item in a huge list.

Perhaps we should test if the current bundle is the main one, and use the cached image initilializer. 
```swift
    let image: NSImage?
    if bundle == Bundle.main {
      image = NSImage(named: NSImage.Name(name))
    } else {
      image = bundle.image(forResource: NSImage.Name(name))
    }```

**Comment by Franz-Wang** [comment]
I agree personally. Especially you have a lot of reusable assets such as in table/collection cells.

**Comment by djbe** [comment]
Unfortunately we can't convert those to constants (`let`), because the images may change because of trait changes, for example light mode --> dark mode.

I'm not sure there's a good solution here TBH.

**Comment by eaigner** [comment]
Honestly this issue kind of makes SwiftGen unusable without cluttering the whole app with global `let`s just to avoid permanently hitting the file system.

**Comment by eaigner** [comment]
I suppose `ImageAsset` could be extended like this

~~~
internal var cachedImage: AssetImageTypeAlias {
    #if os(iOS) || os(tvOS)
    // implement
    #elseif os(OSX)
    AssetImageTypeAlias(named: name)
    #elseif os(watchOS)
    AssetImageTypeAlias(named: name)
    #endif   
}
~~~

This wouldn't break anything, and people who want the cached asset get it.

**Comment by djbe** [comment]
Okay I've done some tests locally with a test macOS app, and using a `let` constant doesn't break trait variations (dark/light). Apparently the NSImage class retains a reference to the name/asset it was loaded from, and reloads itself (or the `NSImageView` does) on trait changes. We could apply the same trick as with colour assets, where we use a `lazy var` to cache assets.

There's a 2nd concern though: once loaded into memory, images will **never** deallocate with this method. With colors this isn't much of an issue because at worst it's a few bytes, but with images, that can result in quite a lot of memory, 100MB+ for a normal sized application. Note that this solution would be applied on all platforms, so also on iPhones and Apple Watches, which are much more memory constrained.

A quick note on OP's `NSImage(named:)` trick for `main` bundle: according to the documentation, those images will only be cached as long as at least 1 instance of that image exists somewhere. As soon as the last instance deallocates, the next time you try to access that asset, it'll be fetched without cache. So it will help in some cases, but not all cases.

With the built-in templates, we must strive for code generation that works correctly and efficiently for everyone. While I'd love nothing more than to have a decent, simple solution for this, we can't generate code that creates memory leaks in our user's apps.

Unless there's a correct solution for everyone, I think it's best for now that if you have performance issues, you can try using a custom template with (for example) the `lazy var` trick I mentioned above.

**Comment by eaigner** [comment]
I have added an extension to my project locally, which solves the issue for now, while preserving the normal caching/dealloc mechanism

```
extension ImageAsset {
    var cachedImage: AssetImageTypeAlias {
        AssetImageTypeAlias(named: AssetImageTypeAlias.Name(name))!
    }
}
```

**Comment by djbe** [comment]
After the tests I did today, the bundle check proposed by @kodlian seems like a good compromise. Most users have their images in their app (i.e. in the `main` bundle), so they'll benefit from this enhancement. See #733 for a PR.

Users with images in other bundles will have to provide their own caching mechanism, as they had to before when directly using `bundle.image(forResource:)`.

**Comment by djbe** [comment]
SwiftGen 6.3.0 has been released, which includes the discussed change 🎉
