### ISSUE TITLE
Does SwitGen enable to specify a main bundle?

### ISSUE THREAD

**Issue by kazuhiro4949** [SwiftGen/SwiftGen#701]
My app has many embeded frameworks. 
They refer to many images and colors from the app target. 

I'd like to use SwiftGen in the embedded frameworks. 
But SwiftGen's Assets class loads a bundle from the same target. 
How can I specify the bundle on SwiftGen config or CLI arguments?

Thanks.

**Comment by AliSoftware** [comment]
Hello @kazuhiro4949 

That's exactly what custom templates are for.

I suggest you duplicate the built-in templates to create a custom one (e.g. `swiftgen templates cat xcassets swift5 >my-xcassets.stencil`) then edit that custom template to adapt the code loading the ressources, so that it does what you need. Then you'll be able to point to that template using the `templatePath:` key in your config file (instead of using `templateName:`

---

For example maybe you'll want your custom template to always search the resources in `Bundle.main` always, instead of using the `Bundle(for: BundleToken.self)` used in built-in templates. Or maybe you'll want to make it search in main bundle first and fallback to the framework bundle. Or maybe you want to make it search in a dedicated and separate `Resource.bundle` where you keep your images and colors… it all depends to your setup, and that's what makes templates powerful: you can adapt them to your exact needs for each specific project!

---

For more information, see [the documentation about creating custom templates](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Creating-your-templates.md#printing-a-template-creating-a-new-template) in the Documentation folder of the repo

**Comment by kazuhiro4949** [comment]
@AliSoftware Thank you for your quick reply!

That makes sense, but the maintenance cost is a little high...
Can I make a new setting to change the bundle?

**Comment by AliSoftware** [comment]
Yeah, I think you could imagine modifying the build-in template to provide an optional template parameter (Say "`bundlesToSearch`"), that will tell which bundles to search for, in order. That parameter would default to `[BundleToken.bundle]` (the bundle where the generated code resides) — which would match what we already use on the current built-in templates — but if the user provides a different value to the param in his config file the template would use that instead.

I think that would allow enough flexibility to cover different cases, like when people have a dedicated resource bundle to use instead of the framework, or when people want to only use the main bundle in all cases, or when people want the generated code to search in the main bundle first, but fallback to the framework bundle, or the opposite …

The goal here is to make the templates which are built-in with SwiftGen not be too specific to special use cases (custom templates are exactly there to support those special use cases that some users might have), otherwise every user with a special case will ask us to support their special case and we'd end up having too many templates to support by SwiftGen itself — and users would also have to wait for a new version of SwiftGen to get their special case supported. We built SwiftGen based on a template system for that reason after all: to give control and ability to users to adapt to their specific needs by providing their own variations of the templates in their project when needed.

So I think having a param just to "use the main bundle instead of the framework's" is too specific to be commonly useful, but having a param that allows to provide a list of bundles to try in order, and letting the user specify if that list is just `[Bundle.main]` or `[Bundle.main, BundleToken.bundle, MyResources.bundle]` or something else depending on their config and needs, might be flexible enough to be included in the build-in templates

---

If you want SwiftGen to support that in the build-in templates, you can submit a PR that would edit the `.stencil` template files change the generated code, and make that code use the `{{ params.bundlesToSearch|default:"[BundleToken.bundle]" }}`.

You can take inspiration on other PRs which added similar params in the past, like maybe https://github.com/SwiftGen/SwiftGen/pull/573

**Comment by kazuhiro4949** [comment]
OK. I'll try that.
