### ISSUE TITLE
Bundle URL returned as nil when registering fonts

### ISSUE THREAD

**Issue by WestFlow127** [SwiftGen/SwiftGen#746]
Hello,

The code generated in my fonts.gen.swift file for retrieving the bundle url used for registering new fonts is returning nil.
I would like a better understanding of why this is happening and the optimal solution.

I am using SwiftGen 6.2.1 and have the following command in my targets Build Phases:
`$PODS_ROOT/SwiftGen/bin/swiftgen fonts -t swift4 magma > magma/Foundation/Generated/Font.gen.swift`

The following full-path is to my font files:
`/Users/weston/Documents/GitHub/ios/magma/Resources/Fonts`

Here are relevant screenshots for clarification:
<img width="295" alt="Screen Shot 2020-07-08 at 3 58 07 PM" src="https://user-images.githubusercontent.com/13974119/86979687-cd996b80-c136-11ea-92a0-bc9891d5694b.png">
<img width="674" alt="Screen Shot 2020-07-08 at 3 57 04 PM" src="https://user-images.githubusercontent.com/13974119/86979694-d1c58900-c136-11ea-8f6f-8f5438b7e33c.png">

Any help would be greatly appreciated, thank you!

**Comment by djbe** [comment]
Right, so to begin with, please open up that folder, we need to see if it contains a folder reference or not. The reason why I'm asking this, is that the path where your fonts end up at (in your app) is very important.

Another question is, did you verify if your fonts are part of your app target like @AliSoftware asked? (in the previous issue)

An easy trick to check both of these items, is to check the "Products/MyApp.app" in Finder, and check it's contents. Are your font files in there? If so, where?

**Comment by WestFlow127** [comment]
Okay, so I did the easy trick and checked, the new fonts are not in the "Products/Magma.app" contents but the original fonts added by a previous dev are there *in the root of the Magma.app contents.

I don't know about folder references tbh. Here is the folder opened up:
<img width="293" alt="Screen Shot 2020-07-08 at 4 56 02 PM" src="https://user-images.githubusercontent.com/13974119/86981611-ea846d80-c13b-11ea-874b-42a7b744e1bd.png">

I also wasn't aware that I needed to add them to the app target :/

**Comment by WestFlow127** [comment]
I thought adding the font files to the font folder within the project structure was adequate.

**Comment by AliSoftware** [comment]
Ok so looking at your screenshot you are not using folder references; which eliminates that case as the potential reason for the bug you're having.

So I think the only thing you likely forgot to do is to add the fonts to the app target — so that Xcode copies them a resources into your app when it compiles it (*)

_(*) Which is something not really related to SwiftGen per se btw, but rather how you add resources to a product in Xcode in general; in other words, you'd have had the same issue even if you weren't using SwiftGen, since your fonts were not copied into your app by Xcode anyway_

**Comment by WestFlow127** [comment]
Okay great, thank you!!

**Comment by AliSoftware** [comment]
@WestFlow127 Btw, unrelated to your original issue, but I noticed in the screenshots and snippets you provided in your issue description that you are using an obsolete and deprecated way to use SwiftGen, and I really encourage you to migrate to the new way that uses a [config file](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md).

Especially, invoking parser subcommands (like `swiftgen fonts`) directly from the command line is deprecated since a while (and since 6.2.1 you actually likely have a new warning that will pop up about you using it), especially because it's not as performant as the new solution introduced back in SwiftGen 5.0 and that [uses a config file](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md). (Starting the next major version (the future SwiftGen 7.0), your build phase won't work anymore if you don't migrate it anyway).

---

To migrate to using a config file, this is not that complicated. You should just follow [the official documentation here](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md), but in a nutshell:
 - Run `swiftgen config init` (at the root of your repo) to let SwiftGen generate an example of a `swiftgen.yml` config file as a starting point
 - Edit that `swiftgen.yml` config file to adjust it to your needs (*).
 - Replace your Build Phase in Xcode to just invoke `$PODS_ROOT/SwiftGen/bin/swiftgen` without any additional parameters. It will read all the necessary parameters and config from the config file

For example to replace your invocation of `$PODS_ROOT/SwiftGen/bin/swiftgen fonts -t swift4 magma > magma/Foundation/Generated/Font.gen.swift` that you're doing in your build phase, your `swiftgen.yml` config file should contain the following YAML:

```yml
fonts:
  inputs: magma
  outputs:
    templateName: swift4
    output: magma/Foundation/Generated/Font.gen.swift
```

If you currently have other invocations of SwiftGen in your build phase for other type of resources than just `fonts`, just add the corresponding entries in your `swiftgen.yml` file too. Your build phase will then just end up invoking SwiftGen only *once* – with `$PODS_ROOT/SwiftGen/bin/swiftgen` – and the config file will tell it all the things to generate at once and in parallel (which is also why it will improve SwiftGen's performance and reduce the time taken by the build phase when compiling your project)

Finally, you can run `Pods/SwiftGen/bin/swiftgen config lint` in your terminal to validate that your config file is correct and see if the commands it will execute matches what you previously had in your build phases.
