### ISSUE TITLE
XCAssets: Custom SFSymbols support (aka symbolset)

### ISSUE THREAD

**Issue by Lutzifer** [SwiftGen/SwiftGen#767]
Would there be interest in supporting custom SFSymbols as described here?
https://developer.apple.com/documentation/uikit/uiimage/creating_custom_symbol_images_for_your_app

Works quite similar to imagesets.

**Comment by djbe** [comment]
Right, those look like image sets, maybe with a different extension to denote the (internal) difference, or no difference at all. 🤷

~Anyone got an example asset catalog with 1 or 2 custom symbols they want to share? Created using the steps described above? I don't have Xcode 12 yet, so can't do it myself.~

I don't see any new type described [in the docs](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/AssetTypes.html#//apple_ref/doc/uid/TP40015170-CH30-SW1) yet, but that may be because Xcode 12 is still in beta.

**Comment by Lutzifer** [comment]
It is working in xcode 11.6 w.o. any Problems for me.

For testing this, the simplest way is to export any symbol as a template from SF Symbols and adding it to an asset catalogue.

**Comment by djbe** [comment]
Huh, I stand corrected, didn't know that was already possible 👍 

How do you use these though? Simply `UIImage.init?(named: String, in: Bundle?, compatibleWith: UITraitCollection?)`? Or is it `UIImage.init?(named: String, in: Bundle?, with: UIImage.Configuration?)`? Probably the latter, to accept configuration for weight, etc...

Can't seem to find an equivalent initializer on macOS (AppKit) 🤔

**Comment by Lutzifer** [comment]
I am using the second initializer:

```
 UIImage(
        named: customSymbolName,
        in: Bundle.main,
        with: UIImage.SymbolConfiguration(pointSize: 32)
      )
```

**Comment by djbe** [comment]
Implemented in SwiftGen 6.5.0, which has been released 🎉

**Comment by eaigner** [comment]
Doesn't seem to be working, `swiftgen` doesn't generate any constants for `symbolset` assets. What am I missing?

**Comment by eaigner** [comment]
Doesn't work on `macOS`. The stencil doesn't include an `#if` case for `macOS` for the `image` property.
