### ISSUE TITLE
Danger is blocking Pull Requests due to missing token

### ISSUE THREAD

**Issue by nicorichard** [SwiftGen/SwiftGen#948]
Examples of affected Pull Requests:

- #935 
- #930 
- #929 
- #927 
- #922
- #916 

... more

- #926 (my own)

---

An admin @SwiftGen/coreteam must go into the project's settings and add or replace an access key which grants public repo access and attach it to the secret accessed by this statement `DANGER_GITHUB_API_TOKEN: ${{ secrets.danger_github_api_token }}`

More info here https://danger.systems/guides/getting_started.html#setting-up-an-access-token

**Comment by AliSoftware** [comment]
I think this was expected for PRs coming from forks, mostly for security reasons — because we don't want to expose the token to forks and then allow them to abuse it.
There are actually some related recommendations in Danger docs itself about security and OSS projects. ~Now that we've migrated to GitHub Actions, and there might be better security options that could open it to forks, but I'm not sure.~ [EDIT: nope, GitHub Actions has the same security measure for PRs from forks, see next comment below]

Note that when you have been given push access to this repo (as is the case for you, and as per our [Community Continuity Guidelines](https://github.com/SwiftGen/SwiftGen/blob/stable/COMMUNITY.md)) you should be able to create branches in this repo (instead of having to use a fork) to create PRs, and those PRs should then be able to run Danger without issue, like has been the case in [this recent PR](https://github.com/SwiftGen/SwiftGen/pull/953)

**Comment by AliSoftware** [comment]
PS: Note that the `DANGER_GITHUB_API_TOKEN` has already been added to GitHub Actions in this repo' settings:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/216089/180029387-83d186c0-e428-405a-a643-89f0abf96a87.png">

And [secrets names are not case-sensitive in GitHub](https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets), so referencing it as `secrets.danger_github_api_token` from the GitHub Actions workflow should work too. In fact, it does work in https://github.com/SwiftGen/SwiftGen/pull/953 🙃 

So I'm not sure what else would be missing? Especially I get why it fails for the couple of PRs from forks you reference above (security reason)… but not sure why it'd fail for dependabot PRs as well though 🤔

**Comment by AliSoftware** [comment]
Note that [the documentation confirms that secrets are not shared with forks](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) in Github Actions (for the same security reasons that I evoke above):

> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

**Comment by djbe** [comment]
As AliSoftware said, this is a security measure, where GitHub does not pass the token along to forks, so that people can't just make a fork and "read" our token. 

Until GitHub provides a mechanism to work around this, we should consider this issue closed.

**Comment by AliSoftware** [comment]
For future reference / documentation, if, as a maintainer, you encounter a PR from a fork in the future, which will thus not be able to run the danger check given the above, here's the process:

1. Create a new branch in this repo, cutting it from the PR that branch is targeting (usually `develop`). Some typical names I often use for those are e.g. `<fork name>/<fork branch name>`, `<fork/author name>/<pr number>` or `run-ci-for/<pr number>`
2. Pull the changes from that fork into that new branch
3. Open a draft PR whose only aim will be to have GitHub trigger the CI checks on that branch. Because the status of CI checks is linked to the commit SHA1 the checks ran on, and both the original PR from the fork and your new draft PR from the local branch will contain the same commits, that will allow the checks on the original PR to be updated as well.
4. Continue pulling new commits from the original PR from the fork into the draft PR as they come, to trigger CI on new commits as necessary
5. Once the original PR gets approved then merged, your draft PR should get auto closed by GitHub, as they both made the same commits land in the same target branch. If not (eg the original PR got new commits that you didn't pull in the draft "sync" PR before the original PR got merged, so they were not equivalent at time of merging), you can close the draft PR manually once the original has landed.
6. Then, following our [Community Continuity Guidelines](https://github.com/SwiftGen/SwiftGen/blob/stable/COMMUNITY.md), you might want to give push access to the contributor who opened that PR from their fork in the first place, so that next time they might want to contribute they can do so directly from the repo instead of their fork, avoiding us to have to do that dance again.

---

So for a PR number 1234 from a contributor who forked the repo under the username/org `Alice/SwiftGen`, trying to merge their branch `featureXYZ` from their fork into our `develop` branch, the commands would look like:

```sh
$ git checkout develop && git pull
$ git checkout -b run-ci-for/alice-1234-featureXYZ
$ git pull git@github.com:Alice/SwiftGen.git featureXYZ
```

**Comment by djbe** [comment]
Created a wiki page with this info: https://github.com/SwiftGen/SwiftGen/wiki/%5BAdmin%5D-Handling-PRs-from-forks
