### ISSUE TITLE
Type 'L10n.Locale' has no member 'current'

### ISSUE THREAD

**Issue by JulesMoorhouse** [SwiftGen/SwiftGen#997]
Can anyone offer any invite into this error...

It's an iOS project.
I'm using iOS 14.5
Xcode 13.2.1

I've tried various version of SwiftGen from 6.5.1, 6.6.0 and 6.6.1

![image](https://user-images.githubusercontent.com/361024/183910416-9e7a1828-eaae-4e58-a12d-88110a6e3a5c.png)

**Comment by JulesMoorhouse** [comment]
The fix for this is... 

```Foundation.Locale.current```

Which is ok if you are using a custom template

**Comment by djbe** [comment]
I don't think this has anything to do with the generated code by SwiftGen? By default we `import Foundation` at the top of the file, and that should be sufficient.

I think the issue here is that you yourself have defined a type called `Locale` that conflicts with the one from Foundation. At that point the compiler will get confused, because it prefers using types you created before the ones from other libraries (such as Foundation). Possible solutions:

- Renaming your custom Locale type to something else
- The one you posted (custom template)
